### ISSUE TITLE
Passing parameter to event

### ISSUE THREAD

**Issue by phuongnd08** [aasm/aasm#123]
Is there a way to passing parameter to event and use a callback to verify the correctness of transition and raise exception if necessary? I know there is a way to do it with alias but it doesn't look right at all.

Here is a simple scenario:

``` ruby
  aasm column: 'state' do
    state :pending, default: true
    state :signed
    state :submitted
    state :confirmed

    event :confirm do
      transitions :to => :confirmed, :on_transition => :verify
    end
end

def verify(params)
  raise error if params.is_invalid?
end
```

I only want to switch the object to confirmed state if user can present a valid parameter so I call:

``` ruby
object.confirm(params)
```

But I'm getting very confusing error: `Event 'confirm' cannot transition from 'submitted'`

**Comment by arthurnn** [comment]
For my own education, is there a PR, or a commit I can take a look to see the difference btwn 3 and 4 where the `confirm(nil, options)` vs `confirm(options)` was changed?
