### ISSUE TITLE
issue with complex state setting behaviour

### ISSUE THREAD

**Issue by glebe** [aasm/aasm#127]
I have a model where state is defined as a relation with another table through `state` association.
So i have setter `aasm_state=(param)` where is set the state as `state=State.find_by_name(param)` and saving it the same time
and getter `aasm_state` which returns `state.name`

Each time I try to change state of the model I get warning because of how AASM treats states:
> https://github.com/aasm/aasm/blob/master/lib/aasm/persistence/active_record_persistence.rb#L96

You can see it's `write_attribute` which has deprecated support of setting instance vars since rails 3.2:
> https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/attribute_methods/write.rb#L33

What do you think, would it be worth considering coins something with it? I think it's not so rare case to have a virtual state attribute and deal with it as I want to, and having the support of AASM setters the same time. 

As of the previous version 3.0.3, non persistent actions (without exclamation at the end) was not causing this deprecation, and now both `action` and `action!` are failing.

**Comment by alto** [comment]
@glebe Does the workaround provided by @opti (thanks a lot for that!) work for you?

**Comment by alto** [comment]
@glebe Please try out the workaround provided by @opti. If it doesn't help feel free to re-open this issue.
