### ISSUE TITLE
Request: initial_state transition on instantiation, instead of at first aasm access

### ISSUE THREAD

**Issue by aarontc** [aasm/aasm#134]
I think it'd be useful for AASM objects to transition to their initial state (and fire callbacks, etc.) immediately upon instantiation. Currently, I'm having to call .aasm#current_state on every object I instantiate, because I'm using timers for automatic transitions in some cases. (And the consumers of the state machines don't care until a callback is fired, so there is no implicit transition or interrogation to cause the aasm initial_state code to fire.)

**Comment by alto** [comment]
@t3hk0d3 Why do you think it'd be unhandy?

**Comment by saneshark** [comment]
You can do this really easily with a after_initialize.

**Comment by lichtamberg** [comment]
@t3hk0d3 Do you want to comment?

I think also that the initialization should be done then the object is initialized...

**Comment by t3hk0d3** [comment]
@lichtamberg 
That was 3 years ago, i can't remember tbh :)

But it sounds like a bad idea to implicitly change state of object (and persist it?).
What if i would like to keep my object uninitialized?

**Comment by lichtamberg** [comment]
Hm yeah maybe... I think I'm also just stressed now because of following bug, which is maybe related? #466

**Comment by t3hk0d3** [comment]
@lichtamberg 
Doesn't look like #466 is related :)

**Comment by aarontc** [comment]
@t3hk0d3 I think it's an antipattern to permit an object to exist uninitialized. 

However, it's been years and no progress has been made so I'm closing this issue to get it out of my pending list.
