### ISSUE TITLE
When used with ActiveRecord, AASM does not check that fields are in the backing db

### ISSUE THREAD

**Issue by michaeldickens** [aasm/aasm#152]
I recently encountered a bug in some code I wrote where I was attempting to access an AASM state from the backing database associated with an ActiveRecord. I hadn't migrated the database, so AASM couldn't find the column in the database. Instead of returning a helpful error, it said, `NoMethodError: undefined method `type' for nil:NilClass`. I discovered that this happens in active_record_persistence.rb:131 when `self.class.columns_hash[self.class.aasm_column.to_s].type` calls `type` on a `nil` value. It would be helpful if AASM checked that the field was in the database before trying to operate on it.

**Comment by fabioperrella** [comment]
@alto I can try to do this. What branch should I use?

**Comment by alto** [comment]
@fabioperrella ?

**Comment by fabioperrella** [comment]
@alto I was looking for some issue to contribute, if you want, I will try to send you a pull request. I asked in what branch should I work on it ?

**Comment by alto** [comment]
@fabioperrella Ah, now I understand. There are two main branches currently worked on, _master_ and _multiple_state_machines_per_class_. I would recommend to branch from _master_, because the multiple one is changing quite a lot.

Thanks for your help. I really appreciate this!

**Comment by fabioperrella** [comment]
@michaeldickens I tryed to reproduce your error but I couldn't. I created a class using aasm and didn't migrated the DB (the column aasm does not exist), then when I called the method .aasm_state, it raised the error NoMethodError: undefined method `aasm_state' for #<Account id: nil, name: "aa">
I used the last stable version of aasm (4.2.0) and rails 4.2.3
Which versions were you using?

**Comment by alto** [comment]
@michaeldickens I just released version `4.6.0` including @anilmaurya's patch. Please re-open if it doesn't work.
