### ISSUE TITLE
Callbacks not running for the initial page state

### ISSUE THREAD

**Issue by aditya-kapoor** [aasm/aasm#156]
This is in reference to the docs mentioned on the Home Page for the gem. The following snippet of code doesn't work at all.

```ruby
class Job
  include AASM

  aasm do
    state :sleeping, :initial => true, :before_enter => :do_something
    state :running

    event :run do
      transitions :from => :sleeping, :to => :running
    end
  end

  def do_something
    debugger
    puts "hiii"
  end
end
```

j = Job.new
j.run # => debugger stops...but it should stop at the time of the initialization of the object.

I think the docs are incorrectly portraying this behavior and is there anything that I am missing. 
Can anyone please advise on this.

**Comment by SirRawlins** [comment]
@aditya-kapoor @alto did either of you guys make much progress on this? I've got a use case at the moment which would benefit from firing these callbacks when entering the initial state.

**Comment by alto** [comment]
@SirRawlins No, I didn't work on this and was – not actively – waiting for @aditya-kapoor .

**Comment by aditya-kapoor** [comment]
Hi everyone,
Due to my ongoing commitments with the current job, I am not able to complete it in time. I would make time for this task and would complete it ASAP.

**Comment by anilmaurya** [comment]
@alto This feature is already implemented and tested in https://github.com/aasm/aasm/blob/master/spec/models/callbacks/basic.rb . Am I missing something or this issue should be closed ?

**Comment by alto** [comment]
@anilmaurya You are right (you start to know _AASM_ better than I do ;) ). Once again, thanks a lot! 

@aditya-kapoor This behaviour (running `:before_enter` and `:after_enter` callbacks on _ActiveRecord_ initialisation) is implemented since version `4.0.4` (see #191 for details).

**Comment by anilmaurya** [comment]
@alto Thanks for the compliment 😎.

**Comment by rubydog** [comment]
I am having similar issue :(. Callbacks are not fired on initial_state. I am using v5.1.1

**Comment by meassinal** [comment]
I'm still facing this issue in a plain ruby object . I'm using v5.5. Anyone has come up with a solution or workaround?
