### ISSUE TITLE
multiple state machines in the same model

### ISSUE THREAD

**Issue by fabioperrella** [aasm/aasm#158]
Hi, this is a feature request!

It would be great if could be possible to use more than 1 state machine in the same model. 
We use gem state_machine and we have some models with more than 1 state machines.
When we tried to upgrade rails from 4.0 to 4.1, we were blocked by issue https://github.com/pluginaweek/state_machine/issues/295 so we tried to use gem aasm but it was not possible

**Comment by Valve** [comment]
+1

**Comment by nofxx** [comment]
-1 An object should not have more than one 'state'.
Remove to a class, persist it embedded. 
E.g: The classic state_machine car example: is a mess!
It would look way better if you had a Gearbox, Windshild and whatnot classes instead of only a Car object that handle all those states.

**Comment by dstosik** [comment]
:+1: to @nofxx

**Comment by Valve** [comment]
@nofxx, in my case I have over a hundred states within one object, and we have a second, more high-level coarse state, which acts as a grouping for multiple fine-grained states. 

For example:
Object on a heap:

created (high level grouping state), may actually be one of:
 * initialized
 * allocated
destroyed (another high level grouping state), may be one of:
* inaccessible
* garbage collected 
* finalized

So in this example we have 5 states, but they can be grouped into 2 high-level states, that give you an immediate idea of the state.
Our actual business case is much more complex, this example is just an oversimplified approximation.

Thanks

**Comment by sepsep** [comment]
+1

**Comment by alto** [comment]
Sorry for the long delay with this issue. This is definitely a bigger change to _AASM_.

**Comment by leofischer** [comment]
+1

**Comment by ShallmentMo** [comment]
I'm facing this problem, too. But I wanna ask if I can use like this

```
class Order
  # State Machine #1 
  aasm(column: 'status') do
    ...
   event :cancel, :before => => Proc.new { self.class.aasm.attribute_name "status"} do
       ...
   end
  end

  # State Machine #2 
  aasm(column: 'pay_status') do
    ...
      event :pay, :before => => Proc.new { self.class.aasm.attribute_name "pay_status"} do
        ...
      end
  end
```

I just set class.aasm.attribute_name before every event trigger, is it OK, or it will bring some problem?

**Comment by ashlinchak** [comment]
You can't. AASM use only one state per model. We all are waiting for 4.2.0 where AASM will have multi state support.

**Comment by ShallmentMo** [comment]
I wanna know whether it will cause some side-effect

**Comment by alto** [comment]
@ShallmentMo The only side-effect I see is that it is error-prone and hard to read and use for other developers. Technically that should even work. Do you use it already like this?

**Comment by ShallmentMo** [comment]
@alto ,I guess I will not use it in this way. I just added some method and made it like event, then looking forward for v4.2

**Comment by sponomarev** [comment]
:+1:

**Comment by fist28** [comment]
@alto When can we expect to close the PR?
I'll need to use state machine with this feature. I have a dilemma - wait for close close #240 or use another gem.

**Comment by alto** [comment]
@fist28 It's still in progress, since a lot of changes have to be made. Works fine for pure Ruby already. I'm currently on the _ActiveRecord_ side of _AASM_. Is it Rails you want to use it for? It would be helpful to get feedback from a real Rails app.

**Comment by fist28** [comment]
My application uses the Rails 4.2

**Comment by alto** [comment]
@fist28 Feel free to try out the branch _multiple_state_machines_per_class_ and let me know how it works. See comments #240 for how to use it.

**Comment by fist28** [comment]
@alto I can't use Transaction support.
If I use this, then i see "test" message on first call SomeModel, for ex. SomeModel.first then I see first record and "test".
```ruby
class SomeModel < ActiveRecord::Base
    include StateMachine::Order::TwistStatus
end
module StateMachine::AlphaState
  def self.included(base)
    base.send(:include, AASM)
    base.send(:aasm, :alpha, column: 'aplha_state_id') do
      ::AlphaState.all.each { |status| state status.id.to_sym }
      event :run, after_commit: p("test") do
        ...
      end
    end
  end
end
```

I tried also to use block `after_commit` inside event but, then I have never seen a message. 
Am I doing something wrong or it's bug?

**Comment by Ricardonacif** [comment]
I'll also try to use that branch and I'll let you know if it's working.

**Comment by alto** [comment]
@Ricardonacif Cheers!

**Comment by Ricardonacif** [comment]
Just tried here, one problem that I faced, the initial state machine of the second field (the one I've just added) gets the string value of the first state machine column initial state. Any idea why? Should I set a default on the database migration?

**Comment by alto** [comment]
@Ricardonacif Let me try to replicate it with a test.

**Comment by alto** [comment]
@Ricardonacif I assume you created your state machines like this:

```ruby
class Example < ActiveRecord::Base
  include AASM

  aasm :search do
    state :initialised, :initial => true
    ...
  end
  aasm :sync do
    state :unsynced, :initial => true
    ...
  end
end
```

Is that correct? If so, please try doing this:

```ruby
class Example < ActiveRecord::Base
  include AASM

  aasm :search, :column => :search do
    state :initialised, :initial => true
    ...
  end
  aasm :sync, :column => :sync do
    state :unsynced, :initial => true
    ...
  end
end
```

That's actually a good question. Maybe I use the state machine's name (like `:search` or `:sync`) as default name for the _ActiveRecord_ column (instead of _AASM_'s default `:aasm_state`). And use the latter only if no state machine name has been provided.

**Comment by alto** [comment]
@Ricardonacif I implemented it that way no. Please try out the latest version (on the _multiple_state_machines_per_class_ branch) with your example. Does it work?

**Comment by danil** [comment]
+1

**Comment by alto** [comment]
Okay. I just released version `4.3.0`, which adds support for multiple state machines per class. Looking forward to see it in the wild and to hear if there are any concerns or problems.

Thanks to everyone for requesting this feature (it's good to know what's important to users)!

**Comment by BKSpurgeon** [comment]
@alto Thank you for this! Just to clarify, if one had multiple state machines on a model/class then we would also need to define the column there as well (with a hash as below), and also ensure there is a corresponding database migration existing? 

```ruby
 aasm :search, :column => :search do
    state :initialised, :initial => true
    ...
  end
  aasm :sync, :column => :sync do
    state :unsynced, :initial => true
    ...
  end
```

**Comment by GabrielLima1** [comment]
Hi guys, i tried used multiple but not working... can you help me ?

```
module States
  extend ActiveSupport::Concern

  included do
    include AASM

    aasm :left, :column => 'left' do
      state :one, :initial => true
      state :two

      event :increment do
        transitions :from => :one, :to => :two
      end
      event :reset do
        transitions :from => :two, :to => :one
      end
    end

    aasm :right, :column => 'right' do
      state :alpha, :initial => true
      state :beta

      event :level_up do
        transitions :from => :alpha, :to => :beta
      end
      event :level_down do
        transitions :from => :beta, :to => :alpha
      end
    end
  end
end
```

```
class Dummy
  include States
end
```

```
# try usage
a = Dummy.new
a.left
```
```
# i got
Traceback (most recent call last):
        1: from (irb):34
NoMethodError (undefined method `left' for #<Dummy:0x0000557eb307b728>)
```
