### ISSUE TITLE
Fire callbacks when changing state field manually

### ISSUE THREAD

**Issue by dkrusenstrahle** [aasm/aasm#161]
Hello,

Do I have to use for example @task.activate! or could the callbacks fire when I change the state field with a normal @task.update (right now it doesn´t).

Thanks!

**Comment by alto** [comment]
No reply since August 2014. Closing for now. Let me know if you have further questions.

**Comment by kevintraver** [comment]
A use case would be if you want to drive a transition for a web api (the state would be passed as form parameters).

**Comment by uxxman** [comment]
Input field coming from an Admin or an end user
