### ISSUE TITLE
after_commit callback behaves strange when cascading events

### ISSUE THREAD

**Issue by bitboxer** [aasm/aasm#163]
I have a state machine that has a little bit of cascading in it with guards that determine in which state the state machine should end up with.

Sadly the after_commit hook does not work for such a use case when using the active record persistence.

What happens is that it will call the after_commit hook of the final state as often as there have been recursions in the state machine and does not call the after_commit hook for all the other states it went through. 

The problem right now is the naiv implementation of the after_commit hook in the active_record_persistence. It will call super for each recursion and when the recursion is done and goes up the chain again it calls the fire_callback for every step, but only with the final state.

I would love to help to fix this, but currently I have no Idea how to do this.

**Comment by alto** [comment]
Closing for now. Let me know if you have further questions or suggestions.
