### ISSUE TITLE
Best way to obtain next to_states for event?

### ISSUE THREAD

**Issue by adamonduty** [aasm/aasm#173]
Given a known event and the current state, how can I get the potential to_states without transitioning to them?

I wrote this code, but I'm not sure if `aasm` has a better approach:

``` ruby
  def to_states_for_event(event_name = :run)
    event = self.class.aasm.events.values.select{|e| e.name == event_name}.first
    event.transitions.select{|t| t.from == aasm.current_state}.map{|t| t.to}
  end
```

In the provided example, this code would return `[:running]`. Is there a better way that would be more likely to survive library refactoring?

**Comment by eric-hemasystems** [comment]
I know this is an old issue but had a similar need so wanted to note my own solution for anyone hitting this in the future:

```ruby
def next_state_on event, *args
  nxt = self.class
    .aasm.state_machine
    .events[event.to_sym]
    .transitions_from_state(state.to_sym)
    .find { _1.allowed? self, *args }
    .to

  aasm.state_object_for_name nxt
end
```

This will actually test each transition on the event to see if it is allowed for the current object. Furthermore it then converts that `to` argument into a full state object so you can get things like the `display_name`.
