### ISSUE TITLE
Problems with guard

### ISSUE THREAD

**Issue by mrcasals** [aasm/aasm#186]
Hi!

I'm upgrading from `aasm` 2.2.1 to 4.0.1 in a Rails app, and I have this state machine defined:

``` ruby
class Order < ActiveRecord::Base
  include AASM
  aasm column: :status do
    state :pending, initial: true
    state :sent
    state :paid

    event :deliver, after: [:fill_shopping_cart, :checkout, :notify_delivery] do
      transitions from: :pending, to: :sent, guard: :due?
    end
  end

  def due?
    due_date <= Date.today
  end
end
```

This is the spec I was using:

``` ruby
describe Order do
  describe 'state machine' do
    describe 'deliver!' do
      it 'does nothing if the order is not due' do
        expect(virtual_order).to receive(:due?).and_return false
        expect(virtual_order).not_to receive(:notify_delivery)
        expect(virtual_order).not_to receive(:fill_shopping_cart)
        expect(virtual_order).not_to receive(:checkout)

        expect(virtual_order.deliver!).to eq(false)
      end
    end
  end
end
```

The spec was passing with `aasm` 2.2.1, but after upgrading to 4.0.1 the test fails because I get an `AASM::InvalidTransition` exception because the guard is failing. I tried moving to the other guard syntax so that the guard does not raise an exception:

``` ruby
class Order < ActiveRecord::Base
  include AASM
  aasm column: :status do
    state :pending, initial: true
    state :sent
    state :paid

    event :deliver, after: [:fill_shopping_cart, :checkout, :notify_delivery] do
      transitions from: :pending, to: :sent do
        guard do
          due?
        end
      end
    end
  end

  def due?
    due_date <= Date.today
  end
end
```

But now the spec fails because it was calling the `order.fill_shopping_cart` method, which should not be called because the guard is failing. 

```
     Failure/Error: expect(order.deliver!).to eq(false)
       (#<Order:0x007f9d938402a0>).fill_shopping_cart(no args)
           expected: 0 times with any arguments
           received: 1 time
```

Am I doing something wrong, or did I just find a bug?

PS: Feel free to change the issue title

**Comment by gabrieljoelc** [comment]
I'm using `4.0.8`, but if I use the `if:` options or the guard block, an `AASM::InvalidTransition` exception when invoking a non-bang event transition method. If I remove the guard entirely, it transitions with no exception.
