### ISSUE TITLE
after_enter fires before state is persisted

### ISSUE THREAD

**Issue by awendt** [aasm/aasm#202]
According to the documentation, `after_enter` is fired after persisting. That's why I'd expect this minimal to work:

```
class Verification < ActiveRecord::Base
  belongs_to :user
  include AASM

  aasm column: 'state', whiny_transitions: false do
    state :initialized, initial: true, after_enter: [:enqueue_something]
    state :confirmed

    event :confirm do
      transitions from: :initialized, to: :confirmed
    end
  end

  def enqueue_something
    persisted? or raise 'Not persisted'
  end
end
```

However, it raises an exception because the record is not persisted yet when `after_enter` fires. See [this gist](https://gist.github.com/awendt/cfa4ec3ba474b2c4825f) for the whole test case.

This is contrary to the documentation and the test [here](https://github.com/aasm/aasm/blob/master/spec/unit/callbacks_spec.rb#L23-L26).

**Comment by alto** [comment]
I will take a look.

**Comment by alto** [comment]
Are you using `confirm!` to fire the event?

**Comment by alto** [comment]
Ah, sorry, I got that wrong. You are not even trying to confirm. `enqueue_something` is part of the initial state.

**Comment by alto** [comment]
So, taking the gist example and your example code above, I assume you are simply instantiating the Verification class:

```ruby
v = Verification.new
# => RuntimeError: Not persisted
```

Is that correct?

The reason for this behaviour is this: _AASM_ makes sure to enter the initial on initialization of the object (using _ActiveRecord_'s `after_initialize` hook). Persistence is run only on firing an event (and only if called as bang method, like `confirm!`). So, basically, there is no event fired on initialization, only the callbacks for the states are fired. I think there shouldn't be an implicit _save_ on `Verification.new`.

Does that make sense?

**Comment by awendt** [comment]
Makes perfect sense, thanks! Closing this.

**Comment by alto** [comment]
:+1:
