### ISSUE TITLE
Adding generator to add migration and aasm skeleton to model

### ISSUE THREAD

**Issue by anilmaurya** [aasm/aasm#205]
Feature request.

After adding aasm to my Gemfile, I was looking for a generator to setup my model and add migration. 

Some thing like this

`rails generate aasm MODEL`

which will add 

    class Model < ActiveRecord::Base
      include AASM

      aasm  do
        
      end
    end

and generate a migration

    class AddModelState < ActiveRecord::Migration
      
       def change
         add_column :models, :aasm_state, :string
       end

     end

But I didn't found any such generator. 

If you think this is good then let me know, I am happy to send PR for this feature.

**Comment by alto** [comment]
@anilmaurya I'm not sure this is really needed. I personally think that a model already exists (in most cases) and people only want to add _AASM_ to it, instead of creating a completely fresh _AASM_ based model from scratch.

Is adding _AASM_ to an existing _ActiveRecord_ class possible with Rails generators as well?

**Comment by anilmaurya** [comment]
@alto yes, its possible. when I said

    which will add

    class Model < ActiveRecord::Base
      include AASM

      aasm  do
 
      end
     end

I meant, If model does not exist then create new model with assm block else append aasm block to the existing model.

**Comment by alto** [comment]
Well, then I'm looking forward to get your pull request @anilmaurya!

**Comment by alto** [comment]
@anilmaurya Can we close this issue then (after having merged #261)?

**Comment by anilmaurya** [comment]
@alto Yeah sure, Finally it is merged🤘. Thank you.
