### ISSUE TITLE
AASM does not work in child class.

### ISSUE THREAD

**Issue by zeitnot** [aasm/aasm#207]
I am using mongoid. 

This is my parent class: 

```ruby
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  include SimpleEnum::Mongoid
  include AASM

  belongs_to :owner, class_name: 'User', inverse_of: :projects

  field :status
  aasm column: :status, whiny_transitions: false do
    state :draft, initial: true
    state :open
    state :running
    state :finished
    state :closed

    event :publish do
      transitions from: :draft, to: :open
    end

    event :run do
      transitions from: :open, to: :running
    end

    event :finish do
      transitions from: :running, to: :finished
    end

    event :close do
      transitions from: :open, to: :closed
    end
  end
end
```

This is child class:

```ruby
class Project::ContentWriting < Project
  field :language, type: String
end
```

When I run the following snippet under rails console it works.
```ruby
p = Project.new
p.save
=> true
```

But when I run this snippet it fails
```ruby
 p = Project::ContentWriting.new
 p.save

 => NoMethodError: undefined method `config' for nil:NilClass
from /home/user/.rvm/gems/ruby-2.1.5@crowdpanthers/gems/aasm-4.0.8/lib/aasm/base.rb:9:in `initialize'

```

**Comment by zeitnot** [comment]
@alto I have analyzed the code but have not found any thing. Is there any improvement with this problem ?

**Comment by alto** [comment]
@zeitnot Sorry for not coming back to this lately. I was busy moving overseas. Do you to mind to help with providing a failing test for this? This would speed up things a lot. I will take a look at the problem as soon as possible (bugs have top priority). Cheers!

**Comment by zeitnot** [comment]
Hi @alto,

I found the problem. The problem is coming form `kaminari` gem. I have created a sample repo [here][0]. If you want you can reproduce the error with this repo. What should I do right now? Should I open an issue on kaminari's page?

[0]: https://github.com/zeitnot/aasm-kaminari

**Comment by alto** [comment]
Let me have a look first :)

**Comment by zeitnot** [comment]
@alto this issue has been fixed by kaminari team. So I am closing this issue.
