### ISSUE TITLE
Auto-save not work in sidekiq perform_async

### ISSUE THREAD

**Issue by lazywei** [aasm/aasm#208]
I have a `Minion` which is a AR class with aasm.
`minion.ready!` works fine in Rails. However, if I call this method in a Sidekiq's `perform_async`, the `minion.ready!` will not save itself. I need to call `minion.save` explicitly.
I'm not sure what's wrong with it. Is there any other information can be useful that I can provide?

Thanks.

**Comment by alto** [comment]
Can I take a look onto your _AASM_ definition for `Minion`? So, if you call `minion.ready!` without Sidekiq the status change is stored automatically, but with Sidekiq it's not? Since I'm not familiar with Sidekiq, how do you use it with `perform_async` and `ready!`?

**Comment by lazywei** [comment]
Sure, thanks for your help!
My code has some changed since this issue, but the underlying problem is the same.

AASM Settings:
```ruby
class Minion < ActiveRecord::Base

  belongs_to :minionable, polymorphic: true

  include AASM

  aasm skip_validation_on_save: true, column: :status do
    state :ready, initial: true
    state :queued
    state :running
    state :terminated
    state :done

    event :queue do
      after do
        create_on_firebase!
      end
      transitions from: [:ready, :done, :terminated], to: :queued
    end

    event :run do
      after do
        update_status_on_firebase!
      end
      transitions from: :queued, to: :running
    end

    event :terminate do
      after do
        update_status_on_firebase!
      end

      transitions from: [:running, :queued], to: :terminated
    end

    event :done do
      after do
        update_status_on_firebase!
      end
      transitions from: :running, to: :done
    end
  end
```

My Sidekiq worker: (please note the comment for problem description)
```ruby
class SomeWorker
  include Sidekiq::Worker
  sidekiq_options retry: false

  def perform(rp_id)
    some_obj = SomeObj.find(rp_id)
    minion = rp.minion
    # I used minion.run!, but it seems it isn't working.
    # So I then use explicit saving ...
    # One more thing to note here, this will not trigger the "after" callback
    # Minion will be saved, and the status will be changed, but the
    # callback (*_on_firebase!) will not be executed until the end of this "perform"
    minion.run && minion.save

    conn = ActiveRecord::Base.connection
    result = conn.execute(some_obj.to_sql)

    # explicit load minion again to prevent race conditions
    minion = Minion.where(id: minion.id).first
    # In case the minion has been destroy
    if minion and !minion.terminated?
      # Do something ... 
      $redis.set(some_obj.redis_key, JSON.generate(realized_content))
      minion.done && minion.save
    end
  end
```

Thanks!

**Comment by alto** [comment]
There are a couple of methods defined per _AASM_ event, see `lib/aasm/base.rb` within the _AASM_ gem. Could you please add a `puts "---------- called with a bang!"` to the method definition of the `run!` bang method? Like this

```
      @klass.send(:define_method, "#{name}!") do |*args, &block|
        puts "----------- called with a bang!"
        aasm.current_event = "#{name}!".to_sym
        aasm_fire_event(name, {:persist => true}, *args, &block)
      end
```

After that, run your code with Sidekiq and the using the bang method `run!` (instead of `run` and `save`). Let's see if the output line _------------- called with bang!_ pops up or not.

**Comment by lazywei** [comment]
Do you mean add the `puts` to the source of aasm (`lib/aasm/base.rb`) or to my code?
I assume you were meaning put it to the `lib/aasm/base.rb`. I'm using aasm 4.1.0, and I put it under the line 79, and I confirm the `------------- called with bang!` pops up.

**Comment by lazywei** [comment]
Sorry, I just found that this is actually caused by race condition. The `create_on_firebase!` will do some async things and will save itself in the end of async things, which results in weird status in the minion. Therefore, this is my stupid bug, not the aasm's. Sorry for wasting your time :(, and thanks for helping me out even it is not aasm's bug.
