### ISSUE TITLE
Graphviz diagrams

### ISSUE THREAD

**Issue by ivantsepp** [aasm/aasm#226]
I was interested in generating state machine diagrams for the classes that use aasm and was researching how I would go about that. In the end, I found out that the other ruby state machine gems have this option. Would you be open to having this feature implemented in aasm? I would be interested in implementing if so!

**Comment by alto** [comment]
Hi @ivantsepp 

I'm undecided. I can imagine that this is of value for some users. On the other hand, I don't want to bloat the codebase and don't think it's the core functionality of a state machine.

What do you think of adding another repo (gem) to the _aasm_ organisation, which adds this functionality to _AASM_?

**Comment by kitop** [comment]
This would be really helpful!
+1 to the idea of doing this in another repo/gem. I'm glad to help if needed!

**Comment by ivantsepp** [comment]
Hey sorry for the late response, a separate repo/gem is a great idea! Any ideas on what the api would look like? Would it be a command line like `aasm-graph file_name.rb`? 

Here was the code I used to generate my graphs (I just made it print out these edge commands which I then copied to the graphviz file)

```
Guest.aasm_events.each do |key, event|
  event.all_transitions.each do |transition|
    puts "#{transition.from} -> #{transition.to} [ label = \"#{key}\" ];"
  end
end
```

**Comment by kitop** [comment]
@ivantsepp that's pretty helpful :)

Just updated your code to work with the latest version of `aasm`:

```ruby
Guest.aasm.events.each do |event|
  event.transitions.each do |transition|
    puts "#{transition.from} -> #{transition.to} [ label = \"#{event.name}\" ];"
  end
end
```

**Comment by alto** [comment]
Let's get started with this. I created a [new repo](https://github.com/aasm/aasm_graph), and invited both of you as collaborators to that project. Looking forward to see things growing!

**Comment by kitop** [comment]
@alto Awesome! Thanks!
Will start coding something this week!

**Comment by ivantsepp** [comment]
:+1: will also find some time this week to help out!

**Comment by alto** [comment]
Let's move this issue over to the [new repo](https://github.com/aasm/aasm_graph).

**Comment by abigoroth** [comment]
I've created a gem which utilize matsuda stateful enum gem. https://github.com/abigoroth/draw_me 

I have not tried @alto method yet. Its a shame.

**Comment by jmgarnier** [comment]
For info, I did a bit of digging to generate a diagram for a Rails 6  and aasm 5.1 App.

I ended up with https://github.com/jmgarnier/aasm_statecharts/tree/rails-6-aasm-upgrade-and-proc-source-goodie
