### ISSUE TITLE
Simple syntacsis

### ISSUE THREAD

**Issue by ilp416** [aasm/aasm#232]
Hi. Thank you for this gem.
Can i use more simple ruby style to define transitions:
transitions from: :fresh, to: :wayting_account
instead
transitions :from => :fresh, :to => :wayting_account
?

**Comment by ilp416** [comment]
Sorry i'm stupid.

**Comment by alto** [comment]
Sure. It's not an _AASM_ feature, it came with Ruby MRI version 1.9 .

**Comment by alto** [comment]
No worries :)
