### ISSUE TITLE
Parameters to events functions

### ISSUE THREAD

**Issue by ilp416** [aasm/aasm#233]
Ok, i need to save who, where and what transition began. For this I have model OrderOperation(order_id, user_id, date, state).
Good idea to use callbacks, but i need to transfer in callback method some parameters (In my case current_user).
How do i can this? Thanks/

**Comment by ilp416** [comment]
Oh, i need to have parameters on event methods, like as
order.making_account! by_user: current_user

**Comment by alto** [comment]
Could you add some more details, please?

How does your model look like? Which callbacks are there? When do you want to provide which parameters to which callback?

Take a look at [the README, section Callbacks](https://github.com/aasm/aasm/#callbacks). I think it helps in your situation.

**Comment by ilp416** [comment]
ok.
order.rb
```ruby
class Order < ActiveRecord::Base
  include AASM
  has_many :order_operations
 ...
 aasm do
    state :fresh, initial: true  #waiting_to_create_an_account
    state :downloaded_to_creating_an_account #creating_an_account
    ...
    state :shipping

    event :download_to_creating_an_account do 
      transitions from: :fresh, to: :downloaded_to_creating_an_account
    end
    ...

  end

  def fix_event event, options={}
    self.order_operations.build(options).event = event
  end

end
```
orders_controller.erb
```ruby
...
def download_all_new_orders
  orders = Order.fresh
  ...
  order.each do |order|
     zip.add order.attachment_file_name, order.name
     order.download_to_creating_an_account!
     order.fix_event "download_to_creating_an_account", user: current_user
  end
end
end
...

```
I can't include fix_event in aasm method, because i can't send current user in event function.
For example i need somethings like this:
```ruby
order.download_to_creating_an_account! by: current_user
```
