### ISSUE TITLE
cannot rename state column

### ISSUE THREAD

**Issue by chrisyeung1121** [aasm/aasm#234]
i tried to change aasm_state to account_state with following code: 

``` Ruby

  include AASM

  aasm :column => :account_state do
    state :unverified, initial: true
    state :approved
    state :suspended
    state :deleted
    state :banned
  end

```

And I added the migration accordingly. 

``` Ruby

class AddAccountStateToUsers < ActiveRecord::Migration
  def change
    add_column :users, :account_state, :string
  end
end

```

However when I try to create an user, following error still applied. I tried restarting rails s and rails c already.

> NoMethodError: undefined method `aasm_state' for #User:0x007f875f6796c8

**Comment by alto** [comment]
Which version of _AASM_ are you using? And do you have a backtrace for me?

**Comment by ankitpatial** [comment]
Hi is this been resolved ?
I am getting the same error i am using aasm (~> 4.3.0).

**Comment by ankitpatial** [comment]
shouldn't it be aasm.state instead of aasm_state ?

**Comment by alto** [comment]
@ankitpatial I don't think so. We are talking about the database column name, and `aasm_state` is _AASM_'s default name.

**Comment by alto** [comment]
@chrisyeung1121 Can you send me the version of _AASM_ you are using, and the backtrace of that exception? Otherwise I will close this ticket.

**Comment by ankitpatial** [comment]
@alto i was talking about the below code
```
NoMethodError: undefined method `aasm_state' for #User:0x007f875f6796c8
```
i was having the similar issue then i realised that with new code i need to do like
```
model.aasm.state #correct
model.aasm_state #wrong
```

**Comment by alto** [comment]
@ankitpatial Are you sure you are using `model.aasm.state`? It's not a method provided by _AASM_. `model.aasm.current_state` exists and return the model's current state, and `model.aasm.states` exists which returns all state objects (or permitted only if you ask for it).

**Comment by ankitpatial** [comment]
Thanks for your patience and digging in, its my misunderstanding of talk, no i am not using that method

Please ignore my earlier comments, i was trying to highlight a point where moving from very old version to current one has difference of calling methods(which was my case).

**Comment by alto** [comment]
@ankitpatial No worries. I was just confused :+1:

**Comment by ankitpatial** [comment]
@alto Thanks for such a fantastic Lib.

**Comment by aldodelgado** [comment]
@alto I'm using version 4.12.3 and I'm getting the same error. Any suggestions?

```NoMethodError: undefined method `aasm_state' for #<Event:0x00007fe2420c1850>
Did you mean?  aasm_state=
               aasm_save
	from (irb):1```

**Comment by aldodelgado** [comment]
@alto I added a ```alias_attribute :aasm_state, [custom_column]``` to my model and this resolved the problem. However if you have any suggestions on how to address this issue, I'm all ears. Cheers!

**Comment by aldodelgado** [comment]
Ok so I ran into a few other issues after setting the alias. So I too a look at the code in the gem and saw that I can assign a position ```:left``` or ```:right```. Once I assigned it and removed the alias. The error went away.

**Comment by ydakuka** [comment]
```
class Model < ActiveRecord::Base
  include AASM

  aasm :column_name column: 'column_name' do
    ...
  end
end
```
Instead of:
```
Model.aasm.states
```
use:
```
Model.aasm(:column_name).states
```

**Comment by anilmaurya** [comment]
Thanks @ydakuka, looks like this issue is not valid anymore therefore closing it.
