### ISSUE TITLE
can't use int type in DB?

### ISSUE THREAD

**Issue by MadisonRong** [aasm/aasm#237]
I have a field called "status" in my DB. Thus, I wanna use AASM without changing structure of my DB.
Can I do that?
here is my code:
```ruby
class Card < ActiveRecord::Base
  include AASM
  enum status: {
    default: 0,
    published: 1,
    deleted: 2
  }

  aasm column: :status, enum: true, skip_validation_on_save: true, no_direct_assignment: true do
    state :default, initial: true
    state :published
    state :deleted

    event :publish do
      transitions from: :default, to: :published
    end

    event :delete do
      transitions from: :published, to: :deleted
    end
  end
 end
```

And, no matter I called `card.publish` or `card.delete`, I got this error below:
```ruby
NoMethodError: undefined method `name' for nil:NilClass
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/core/state.rb:15:in `=='
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/instance_base.rb:61:in `block in state_object_for_name'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/instance_base.rb:61:in `each'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/instance_base.rb:61:in `find'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/instance_base.rb:61:in `state_object_for_name'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/aasm.rb:62:in `aasm_fire_event'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/persistence/active_record_persistence.rb:175:in `aasm_fire_event'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/aasm-4.1.1/lib/aasm/base.rb:86:in `block in event'
	from (irb):6
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/MadisonRong/.rvm/gems/ruby-2.0.0-p598/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by alto** [comment]
Is the example correct? Shouldn't it be 

```ruby
enum status:...
```

and

```ruby
  aasm column: :status, enum: true,...
```

?

**Comment by MadisonRong** [comment]
oh, I'm sorry. I have edit my code.And I do it like you just commented but it also doesn't work.

**Comment by alto** [comment]
With the same error message and backtrace?

**Comment by MadisonRong** [comment]
oh, forgot to update that.wait a sec...

**Comment by MadisonRong** [comment]
ok, done...

**Comment by MadisonRong** [comment]
damm, I just created a new project for test. It worked!!_(:з」∠)_can you tell me why

**Comment by alto** [comment]
No, but I copied your example into the test suite, and it worked, too. Maybe some dependency? Hmmm...

**Comment by MadisonRong** [comment]
I found that I will get that error when using a string type in my DB.Can't use enum when state is string type in DB?

**Comment by MadisonRong** [comment]
ok, now, it's more wired.I change my column back to integer type, and all setting like example.I can't run in sidekiq, but it worked in rails c.

**Comment by alto** [comment]
You don't get the error, if the table column is defined as `integer` but with `string`? I double-checked that in the _AASM_ test suite, and no, that doesn't make any difference. It works with both, `string` and `integer`. 

Question: it works in your new app, you say, right? Does it work with `string` and `integer`?

**Comment by MadisonRong** [comment]
Sorry for replying you so long.I have something to process over the past 10 days.
I try it in a new app today.And I found that using `enum` when type of field is `string` will get the error aforementioned.

**Comment by anilmaurya** [comment]
@MadisonRong You are getting this error because you have defined field type as `string` but `enum` values is `integer`, therefore ActiveRecord is not able to map enum key with column value.

To fix this issue, declare enum as

```
class Card < ActiveRecord::Base
  include AASM
  enum status: {
    default: "0",
    published: "1",
    deleted: "2"
  }
```

**Comment by MadisonRong** [comment]
@anilmaurya yep, you are right. Thanks....

**Comment by alto** [comment]
@anilmaurya Again, thanks for your help! I really appreciate it!
