### ISSUE TITLE
`before` not available on `transitions` block argument

### ISSUE THREAD

**Issue by trek** [aasm/aasm#246]
valid keys there are `[:on_transition, :guard, :after]`

```
 #<DslHelper::Proxy:0x00000115c399f0
 @options=
  {:from=>:something, :to=>:something_else},
 @source=#<AASM::Core::Transition:0x00000115c3a300>,
 @valid_keys=[:on_transition, :guard, :after]>
```

But the README shows an example of using before:

```
      transitions :from => :sleeping, :to => :running, :after => Proc.new {|*args| set_process(*args) } do
        before do
          log('Preparing to run')
        end
      end
```

**Comment by alto** [comment]
I will take a look.

**Comment by alto** [comment]
@trek Indeed, the `:before` callback on transitions is not supported. With #251 the README got changed accordingly.

Do you have a use case for the callback on transitions?

**Comment by trek** [comment]
No use cases. Just wanted to know which was correct, docs or impl.

**Comment by alto** [comment]
Can I close the issue then?
