### ISSUE TITLE
bang! method not working with custom validator

### ISSUE THREAD

**Issue by reicheltd** [aasm/aasm#249]
I am trying to lock down my object attributes to prevent the object from being deleted, when it has  the `fooled ` state. I cant transition to `fooled` when I have the validator in place. Rails 4.2.3 with aasm 4.2.0
  
    state :fooled
    event :fool do
       transitions from: :some_state, to: :fooled
    end

    validate  :lock_down_attributes, if: :fooled?

    def lock_down_attributes
        message = "#{self} was fooled"
        errors.add(:attribute1, message)        if attribute1_changed?
        errors.add(:attribute2, message)        if attribute2_changed?
        errors.add(:attribute3, message)        if attribute3_changed?
    end

    Object.some_state? -> true
    Object.may_fool? -> true
    Object.fool! -> false

When I remove the validator, it works like it should. Thx for responses!

**Comment by alto** [comment]
@reicheltd How did you configure _AASM_ for that particular class (did you overwrite the default behaviour for `:skip_validation_on_save` for example)? What do the three methods `attribute*_changed?` do? Is there actually a validation error happening? Maybe you could show me what `Object.errors.full_messages` looks like?

**Comment by reicheltd** [comment]
@alto Hey. My aasm config for that class is very simple. Just some states and some transitions. Like in the aasm docs. No additional params, callbacks or options. The `_changed?` method is a rails method http://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changed-3F that tells me if an attributes has changed. Yes there is a validation error, its the message from the `lock_down_attributes` method.

**Comment by anilmaurya** [comment]
@reicheltd If you use bang ( ! ) method than AASM persist changed state by calling `save` on object. 

In your case, you have  validation errors when AASM tries to save object that's why its not working for you.

`Object` state is `fooled` when it is being saved hence validation condition (`if: :fooled?`) is satisfied and it checks for `:lock_down_attributes`.

You should write something like this

```
validate  :lock_down_attributes

def lock_down_attributes
   if (![:fooled].include?(aasm.to_state) && self.aasm_state == "fooled")
      message = "#{self} was fooled"
      errors.add(:attribute1, message)        if attribute1_changed?
      errors.add(:attribute2, message)        if attribute2_changed?
      errors.add(:attribute3, message)        if attribute3_changed?
   end
end

# ![:fooled].include?(aasm.to_state) returns false when transitioning to :fooled state, 
hence validation won't be invoked when transition to :fooled state.

```

**Comment by reicheltd** [comment]
Hey @anilmaurya this seems to work. Thanks!

**Comment by anilmaurya** [comment]
@reicheltd welcome :relaxed: , @alto I think you can close this issue now.

**Comment by alto** [comment]
@anilmaurya  Allright. Thanks a lot for your help!
