### ISSUE TITLE
How to return desired value after `error do`

### ISSUE THREAD

**Issue by zenati** [aasm/aasm#250]
``` ruby
aasm whiny_transitions: false do
  state :not_paid
  state :paid

  event :paid, guards: [:payable?] do
    transitions from: :not_paid, to: :paid

    error do |exception|
      # Logging exception
      # how to return false here?
    end
  end
end

def payable?
  # API Calls...
  false
end
```

I'm using guards with error callback. What I need to acheive is
- If guard returns false, than error callback is invoked and false is returned on `.paid?` call

Is it possible?

Using the code above, the error cb is never called.

**Comment by alto** [comment]
@zenati It's currently not possible, but it's actually a good idea. I would like to keep the `:error` callback for real errors though. What do you think of this:

```ruby
class MyClass
  aasm whiny_transitions: false do
    state :not_paid
    state :paid

    event :paid, guards: [:payable?] do
      transitions from: :not_paid, to: :paid

      failure do
        # handle failure
      end
    end
  end

  def payable?
    # API Calls...
    false
  end
end

MyClass.new.paid
# calls the :failure callback and returns false (because whiny_transitions is set to false)
# => false
```

**Comment by javiercr** [comment]
+1 for adding `failure` to the DSL :)

**Comment by alto** [comment]
@zenati Would that suit you as well?

**Comment by zenati** [comment]
@alto :+1:

**Comment by lichtamberg** [comment]
Whats the status of this ticket? It's closed, but I cannot find anything about it in the readme? Or did I miss something?
