### ISSUE TITLE
Problem with fixtures?

### ISSUE THREAD

**Issue by daniely** [aasm/aasm#254]
If I add aasm (with a default state) to my `User` model and create a user instance through a fixture it will not have the default state set. This causes problems because any transitions from one state to another will not work since the default state is `nil`.

This might not be a problem with aasm per se but I'm wondering what's the best way to deal with this. Maybe some documentation could be added at least to let users know of this little issue? It took me awhile to figure out that the missing initial state was causing problems.

**Comment by reidmorrison** [comment]
If you are using `FactoryGirl`, try adding the default state to your `User` factory.

Although not ideal it sounds like the factory being used is bypassing the `after_initialize` callback that is used to populate the default state.

**Comment by daniely** [comment]
Thanks for the comment. However, I'm not using `FactoryGirl` for this particular project. Just fixtures.

**Comment by alto** [comment]
@daniely I'm sorry, but I cannot reproduce the error. I just created a fresh Rails app, added my first model `Booking` (with a `:name` and the _AASM_ column `:status`)

```ruby
class Booking < ActiveRecord::Base
  include AASM
  aasm column: :status do
    state :pending, initial: true
    state :confirmed
  end
end
```

and this fixture

```
dude:
  name: Dude
```

Within one of the tests I can happily do this:

```ruby
b = bookings(:dude)
b.aasm.current_state
# => :pending
```

Maybe you can check if something overriding or bypassing the class's `after_initialize` callback?

**Comment by daniely** [comment]
Thanks for taking a look at this. Just FYI the version I am using is 3.2.1.

I'll try digging deeper in my code to see what's going on.

On Wed, Oct 21, 2015 at 10:09 PM, Thorsten Böttger <notifications@github.com

**Comment by alto** [comment]
@daniely Ah, that's indeed a very important information. Prior to version `4.0.4` _AASM_ did not set the initial state on _ActiveRecord_ initialisation. 

Please upgrade to version `4.0.4` (at least). See [README_FROM_VERSION_3_TO_4](https://github.com/aasm/aasm/blob/master/README_FROM_VERSION_3_TO_4.md) for doing this.
