### ISSUE TITLE
Why multiple to states are accepted?

### ISSUE THREAD

**Issue by fabn** [aasm/aasm#255]
I just made a typo in one of my projects by declaring multiple to states in a `to` param as in

```ruby
state :usable
state :archived

event :something do
  transitions from: [:usable, :archived], to: [:usable, :archived]
end
```

When I call `job.something` final state is always `usable`. What is the reason to accept an array as `to` arguments? 

I wasn't able to find any example in the documentation with an array in `to` states, so I assume this is a bug.

Shouldn't aasm raise an error in this case?

**Comment by alto** [comment]
@fabn Very interesting! Thanks for pointing that out, I consider it a bug :+1:

**Comment by alto** [comment]
@fabn Haha, now I got lost in my own gem. It's actually not a bug, it's a feature (did I just say this?). But it's one I don't use myself.

Consider this:

```ruby
class MyClass
  aasm do
    state :pending, initial: true
    state :running
    state :processed

    event process do
      transitions from: :pending, to: [:running, :processed]
    end
  end
end
```

Then you can do this:

```ruby
obj = MyClass.new

obj.process(:processed)
obj.aasm.current_state
# => :processed

# or
obj.process(:running)
obj.aasm.current_state
# => :running
```

As I said, I don't need nor use it. But it's possible. It's not reflected in the README, as I want to keep that readable and concise.

**Comment by fabn** [comment]
@alto got it, thanks for the explanation.

**Comment by shishirsharma** [comment]
Can we use some kind of hook or lambda for selecting one of these to state.  This way we could club state selection process in our aasm code.
