### ISSUE TITLE
SystemStackError: stack level too deep happened 

### ISSUE THREAD

**Issue by tengcong** [aasm/aasm#257]
just as the example:

```
job = Job.new
job.sleeping? # => true
job.may_run?  # => true
job.run
job.running?  # => true
job.sleeping? # => false
job.may_run?  # => false
job.run       # => raise SystemStackError: stack level too deep
```

activerecord 4.2.4

**Comment by alto** [comment]
@tengcong Which version of _AASM_ are you using?

**Comment by tengcong** [comment]
aasm (4.3.0)

**Comment by alto** [comment]
@tengcong Hmmm...

Do you have some sort of state machine definition or a backtrace for me?

**Comment by tengcong** [comment]
```
 aasm do
    state :pending, initial: true
    state :approving
    state :approved

    event :preview do
      transitions from: :pending, to: :approving
    end
    event :pass do
      transitions from: :approving, to: :approved
    end
end
```

the only backtrace is 
`SystemStackError: stack level too deep`

my current workaround is to add
`whiny_transitions: false` to avoid raising errors

**Comment by alto** [comment]
So, the error is gone once you add `whiny_transitions: false`?

**Comment by tengcong** [comment]
yes, it just return `false` instead of rasing `SystemStackError: stack level too deep`

**Comment by alto** [comment]
Can you try out to rescue the `SystemStackError` and print the backtrace?

**Comment by tengcong** [comment]
exception.class => SystemStackError
exception.message => stack level too deep
exception.backtrace => /Users/congteng/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:187

**Comment by alto** [comment]
One line is the whole backtrace? Are you sure?

**Comment by tengcong** [comment]
![image](https://cloud.githubusercontent.com/assets/2024403/9985068/0f2d7942-6057-11e5-89a0-fa41112b81fe.png)

**Comment by alto** [comment]
Grmpf... Okay, I believe you ;)

**Comment by alto** [comment]
Do you have a `method_missing` in your model?

**Comment by alto** [comment]
Or do you use a self-written transaction around the `pass!` call?

**Comment by tengcong** [comment]
```
class Project < ActiveRecord::Base
  include AASM
  belongs_to :user
  aasm whiny_transitions: false do
    state :pending, initial: true
    state :approving
    state :approved
    state :unapproved
    event :preview do
      transitions from: :pending, to: :approving
    end
    event :pass do
      transitions from: :approving, to: :approved
    end
    event :discard do
      transitions from: :approving, to: :unapproved
    end
  end
end
```

**Comment by alto** [comment]
Hmm, that doesn't look all too special. :(

**Comment by alto** [comment]
How to reproduce the exception? Like this?

```ruby
p = Project.new
p.preview!
p.pass!
```

Or do you anything special? Can you reproduce the error in the Rails console?

**Comment by tengcong** [comment]
```
p = Project.create 
p.preview! # ok
```

```
p = Project.create
p.pass! # SystemStackError: stack level too deep
```

**Comment by alto** [comment]
I can't replicate the error. If I call – using your `Project` example code, but leave away the `whiny_transitions` options – `Project.create.pass!`, I get

```ruby
```

**Comment by alto** [comment]
Maybe you could debug into your code or at least put some debug `puts` into `AASM::InvalidTransition: Event 'pass' cannot transition from 'pending'` for example to narrow down the problem.

**Comment by alto** [comment]
@tengcong Closing this ticket now. Feel free to re-open if you need help.

**Comment by millie** [comment]
I've got a similar issue. Did you figure this out @tengcong? `:whiny_transitions => false` didn't help me...

**Comment by millie** [comment]
If it's any help to others, I found that having an aasm event called `:send` caused the error, and renaming it made it go away. I have no idea why.

'''ruby
aasm :column => 'status' do

    state :created, :initial => true
    state :estimated
    state :accepted
    state :invoiced
    state :paid
    state :canceled

    # event :send do 
   ### bad news ^^    ... but below works ##
    event :send_estimate do 
      transitions :from => :created, :to => :estimated
    end

    event :accept do
      transitions :from => :estimated, :to => :accepted
    end

    event :invoice do
      transitions :from => [:estimated, :accepted], :to => :invoiced
    end

    event :pay do
      transitions :from => :invoiced, :to => :paid
    end

    event :cancel do
      transitions :from => [:accepted, :estimated, :invoiced, :paid], :to => :canceled
    end

  end
'''

**Comment by alto** [comment]
@millie Hmm, thanks for the hint. That's right, until now _AASM_ doesn't really like `send` events, but I will have a look at this.

@tengcong Could that be your case, too?

**Comment by alto** [comment]
Released version `4.7.0` including a fix for the `:send` (as event name) problem.

**Comment by mmahalwy** [comment]
Good catch @millie !

**Comment by jm96441n** [comment]
Ran into this same problem, not using `:send` though:

**Comment by timokleemann** [comment]
I am using version `5.0.1` and still can't use `send` as event name. 

On the console I am getting `WARN -- : Invoice: overriding method 'send'!` before it crashes.

What am I missing?
