### ISSUE TITLE
Allow State#for_select method to output IDs 

### ISSUE THREAD

**Issue by jamesinfmz** [aasm/aasm#260]
Currently the `for_select` method looks like this:

    def for_select
      [display_name, name.to_s]
    end

For database-backed states, it would be useful this the ability for this column return something like `[display_name, <ID column value>]`.

**Comment by alto** [comment]
@jamesinfmz Can you provide an example for `<ID column value>` (id of which item) ?

**Comment by alto** [comment]
@jamesinfmz Re-open if still needed.
