### ISSUE TITLE
bang methods don't raise validation errors leading to hard to trace errors

### ISSUE THREAD

**Issue by PragTob** [aasm/aasm#262]
First of all, thanks for doing aasm :+1:

When a validation error occurs only in a state that I transition to, the `bang!` method returns false, I stay in the old state and I have no idea why the transition failed.

What I would like to have is to have some sort of access to the error, or even better a configuration option that the `bang!` methods raise on validation errors. Maybe that exists and I just don't know.

This way this was very hard to track down, why an object did not transition.

Now, taking this simple test class:

```ruby
class AasmTest < ActiveRecord::Base
  include AASM

  validates :number, numericality: true, if: :failing?

  aasm column: 'state' do
    state :init, intial: true
    state :failing

    event :bam do
      transitions from: :init, to: :failing
    end
  end
end
```

And now take it for a spin:

```
[2] pry(main)> a = AasmTest.new
=> #<AasmTest:0x0000000c6fcac8 id: nil, state: nil, number: nil>
[3] pry(main)> a.valid?
=> true
[4] pry(main)> a.bam!
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
=> false
[5] pry(main)> a.valid?
=> true
[6] pry(main)> # I have no idea why it did not transition as it is valid, there is no guard etc.
[7] pry(main)> a.bam
   (0.1ms)  BEGIN
   (0.1ms)  COMMIT
=> true
[8] pry(main)> a.valid?
=> false
[9] pry(main)> a.errors
=> #<ActiveModel::Errors:0x0000000c2d9838 @base=#<AasmTest:0x0000000c6fcac8 id: nil, state: "failing", number: nil>, @messages={:number=>["ist keine Zahl"]}>
[10] pry(main)> a.save!
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
ActiveRecord::RecordInvalid: Gültigkeitsprüfung ist fehlgeschlagen: Number ist keine Zahl
from /home/tobi/.rvm/gems/ruby-2.2.3@liefery-backend/gems/activerecord-4.2.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
[11] pry(main)> # ah, that's why....
```

Thanks!

edit: I guess this somehow relates to #249 but I'm asking for a different thing :)

**Comment by anilmaurya** [comment]
@PragTob This is not related to #249 . 
Currently when you do `a.bam` then state is transitioned from `init`  to `failing`  but its not persisted in database But using `a.bam!` persist changes to database by calling `save` on object.

Its a feature request rather than a bug. May be a configuration option like `raise_error: true` which will save object using `save!` method.

@alto  its required or not?

**Comment by anilmaurya** [comment]
There is already a config option  `whiny_transitions` which is by default true. In my opinion bang method should call  `save!` unless `whiny_transitions: false`

**Comment by reidmorrison** [comment]
:+1 This one caught me unawares too recently. Had not researched it further yet.

Should not be hard to submit a pull request for this change.

**Comment by reidmorrison** [comment]
On MongoMapper I am using the following patch for now:
```ruby
    def aasm_write_state(state, name=:default)
      attr_name = self.class.aasm(name).attribute_name
      old_value = read_attribute(attr_name)
      write_attribute(attr_name, state)

      begin
        if aasm_skipping_validations(name)
          saved = save(validate: false)
          write_attribute(attr_name, old_value) unless saved
          saved
        else
          save!
        end
      rescue Exception => exc
        write_attribute(attr_name, old_value)
        raise(exc)
      end
    end
```

For ActiveRecord the following should work:
```ruby
    def aasm_write_state(state, name=:default)
      attr_name = self.class.aasm(name).attribute_name
      old_value = read_attribute(attr_name)
      aasm_write_attribute(state, name)

      begin
        if aasm_skipping_validations(name)
          saved = save(validate: false)
          write_attribute(attr_name, old_value) unless saved
          saved
        else
          save!
        end
      rescue Exception => exc
        write_attribute(attr_name, old_value)
        raise(exc)
      end
    end
```

@alto do have any thoughts on what config option we should use to control the whiny validations behavior? I can also submit a PR if that would help?

**Comment by alto** [comment]
@anilmaurya I agree, it could be combined with the `:whiny_transitions` option. Thus, use `save` if `:whiny_transitions => false` and `save!` if `:whiny_transitions => true`.

@PragTob What do you think?

**Comment by PragTob** [comment]
@alto sounds good, although I'd prefer a separate option. With whiny transitions it'd be a breaking Major version version type of change and whiny doesn't imply "raise  error and hell" - so imo that'd speak for a new option but your call :)

**Comment by dantethegrey** [comment]
If anyone was interested I found workaround using  `aasm_event_failed`, below is my implementation on an AR model class including `aasm`

```
def aasm_event_failed(event_name, new_state)
  if errors.any?
    raise ActiveRecord::RecordInvalid.new(self)
  end
end
```

PS: is it on purpose `aasm_event_failed` isn't documented? Eg .I might get surprised it's lost with next release;) 

Thanks

**Comment by rringler** [comment]
:+1:  on bang methods calling `#save!`

**Comment by EricDurante** [comment]
I ended up using one of the provided callbacks to get the behavior that I wanted.

```ruby
class MyModel < ActiveRecord::Base
  include AASM

  aasm do
    # state declarations and things
    ensure_on_all_events :raise_validation_errors
  end

  private

  def raise_validation_errors
    raise ActiveRecord::RecordInvalid.new(self) if errors.any?
  end
end
```

**Comment by jmcnevin** [comment]
Wow, this one just bit me as well.  I feel like the bang method of event transitions should never be able to silently return `false`.  Would anyone ever want or expect the bang method to behave that way?

**Comment by Wildebeest** [comment]
@alto I took a crack at implementing this, since this behavior was unexpected to us as well. Would you mind taking a look at letting me know what you think?

**Comment by alto** [comment]
I just released version `4.11.0` including #366 .

**Comment by PragTob** [comment]
should this be closed now or will it be closed with 5.0 then? 

Thanks @Wildebeest and @alto !

**Comment by alto** [comment]
@PragTob This one can be closed. I somehow expected it to be closed automatically after merging #366.

**Comment by arthurnn** [comment]
Thanks for working on this everyone ❤️  got the same issue over here.

**Comment by one-more-alex** [comment]
For those who not understood the solution.
Need to use whiny_persistence flag.

`aasm ... :whiny_persistence => true do`

**Comment by AlexVentura** [comment]
@one-more-alex I'm one of the ones whom not understand the solution pretty well, so can you share your a full model example running validations before transitioning to another state, please?

**Comment by constantm** [comment]
@AlexVentura you need to explicitly set `whiny_persistence` to `true` when setting up the state machine in your model, else it just returns false instead of raising an exception, which is usually expected from bang methods.
