### ISSUE TITLE
Can we add callbacks to parent events in child classes?

### ISSUE THREAD

**Issue by reidmorrison** [aasm/aasm#267]
If we create a base class Job that has a before event callback defined:

```ruby
class Job
  include MongoMapper::Document
  include AASM

  key :state, Symbol, default: :queued

  aasm column: :state do
    state :queued, initial: true
    state :running

    event :start, before: :before_start do
      transitions from: :queued, to: :running
    end
  end

  def before_start
    puts "BEFORE START"
  end
end

j1 = Job.new
j1.start

# => BEFORE START
```

Then we create a child class and want to add more callbacks:

```ruby
class Job2 < Job
  aasm do
    event :start, after: :after_start
  end

  def after_start
    puts "AFTER START"
  end
end

j2 = Job2.new
j2.start

# => AASM::InvalidTransition: AASM::InvalidTransition
```

It appears that `event` completely overrides the previous definition for the event so we need to completely respecify the parent event to extend it.

```ruby
class Job2 < Job
  aasm do
    event :start, before: :before_start, after: :after_start  do
      transitions from: :queued, to: :running
    end
  end

  def after_start
    puts "AFTER START"
  end
end

j2 = Job2.new
j2.start

# => BEFORE START
# => AFTER START
```

I am happy to create a pull request if you have any suggestions on how we should go about allowing child classes to modify parent event definitions?

Maybe add a method that can be called outside the event to add callbacks to it?

```ruby
after_transition on: :start, :do => :after_start
```

Or, maybe dynamically define methods in the aasm block for adding callbacks for each event?

```ruby
class Job2 < Job
  aasm do
    after_start :show_started
  end

  def show_started
    puts "AFTER START"
  end
end
```

**Comment by anilmaurya** [comment]
To add another callback in event, you can do 

```
class Job2 < Job
 
 def initialize
    event = self.class.aasm.events.select{|e| e.name == :start}[0]
    event.options[:after] = [:show_started]
  end

  def show_started
    puts "AFTER START"
  end
end
```

**Comment by reidmorrison** [comment]
Unfortunately changing the options in the child class `Job2` also changes the options in class `Job`. As a result when starting `Job` it now fails trying to call `show_started`

```ruby
j1 = Job.new
j1.start
# => BEFORE START
# => NoMethodError: NoMethodError: undefined method `show_started' for #<Job _id: BSON::ObjectId('5620f107a26ec04db6000003'), _type: "Job", state: :running>:Job
```

Unfortunately the AASM `inherited` implementation only does a shallow clone of the state machine information, which results in shared event definitions.

**Comment by anilmaurya** [comment]
@reidmorrison You are right. I didn't consider this issue.

**Comment by reidmorrison** [comment]
@anilmaurya I still think you are on the right track, we have just bumped up against a separate inheritance cloning issue.

Adding the following patches allows your example above to work:
```ruby
module AASM
  class StateMachine
    def initialize_copy(orig)
      super
      @states = orig.states.collect { |state| state.clone }
      @events = {}
      orig.events.each_pair { |name, event| @events[name] = event.clone }
    end
  end
end

module AASM::Core
  class Event
    def initialize_copy(orig)
      super
      # TODO @transitions, @guards, @unless
      @options = {}
      orig.options.each_pair { |name, setting| @options[name] = setting.is_a?(Symbol) ? setting : setting.clone }
    end
  end
end

# TODO clone transition child elements
```

Looks like I need need to turn the inheritance fix into a pull request.

**Comment by anilmaurya** [comment]
@reidmorrison Looks good to me. :+1:

**Comment by reidmorrison** [comment]
Fixed with PR https://github.com/aasm/aasm/pull/269
