### ISSUE TITLE
Wiki pages?

### ISSUE THREAD

**Issue by rstormsf** [aasm/aasm#271]
Am I tripping? Where are they all gone ?

**Comment by rstormsf** [comment]
Sorry I was confused with https://github.com/sferik/rails_admin/wiki page. I was like - where are all docs?

**Comment by alto** [comment]
No worries :+1:

**Comment by rstormsf** [comment]
Fighting with https://github.com/zcpdog/rails_admin_aasm - can't figure out why the button doesn't send anything to controller
https://github.com/zcpdog/rails_admin_aasm/issues/4
I setup breakpoints into https://github.com/zcpdog/rails_admin_aasm/blob/master/lib/rails_admin_aasm/action.rb - nothing gets executed :-(

**Comment by troyanryller** [comment]
try
```ruby
      aasm skip_validation_on_save: true do
```
mb u have some validations that fails...
