### ISSUE TITLE
Serialize all possible transitions

### ISSUE THREAD

**Issue by sgringwe** [aasm/aasm#274]
Our application is becoming frontend heavy. The may_xxx? calls are great in ruby, but there's no good way to send that to frontend other than 1-by-1 explicitly. Any way to send all possible transitions in a single method? Which returns a hash of allowed transitions?

**Comment by hspazio** [comment]
hi @sgringwe, I've used the following method in the model class that implements *aasm*:
```ruby
  def permitted_statuses
    aasm.events(permitted: true).map(&:name)
  end
```
which returns an array of symbols. If your transition is there the `may_xxx?` should also return `true`.

**Comment by sgringwe** [comment]
@hspazio thanks! that works, and looking back AASM probably shouldn't be worried about serialization anyways.

**Comment by alto** [comment]
@sgringwe Sorry for coming back to you so late.

Thanks to @hspazio for jumping in and helping out. 

Can I close this issue then?
