### ISSUE TITLE
after_commit callback not works by using non bang event call

### ISSUE THREAD

**Issue by lonre** [aasm/aasm#285]
```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '4.2.5'
  gem 'aasm', '~> 4.4.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'
require 'aasm'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :jobs, force: true do |t|
    t.string :status
  end
end

class Job < ActiveRecord::Base
  include AASM

  attr_accessor :committed

  aasm column: :status do
    state :sleeping, initial: true, before_enter: :init_committed
    state :running

    event :run, after_commit: :do_something_after_commit do
      transitions from: :sleeping, to: :running
    end
  end

  private

  def init_committed
    self.committed = false
  end

  def do_something_after_commit
    self.committed = true
  end
end

class BugTest < Minitest::Test
  def test_do_something_after_commit_works
    job = Job.new
    job.run!

    assert job.committed
  end

  def test_do_something_after_commit_not_works
    job = Job.new
    job.run
    job.save

    assert !job.committed
  end
end
```

**Comment by anilmaurya** [comment]
@lonre This is the desired behaviour of `after_commit` callback.

If you read https://github.com/aasm/aasm#transaction-support carefully, then you will see statement - 

```
If you want to make sure a depending action happens only after the transaction is committed, use the after_commit callback
```

`transaction is committed` means results is persisted to the database.

When you call `job.run!` then `run` event is fired and `job` is saved to database that's why `after_commit` callback is called.

When you call `job.run` then `run` event is fired but `job` is not saved to database that's why `after_commit` callback is not called.

If you want to write a method which should be invoked in both cases then you should probably use `after` callback.

**Comment by lonre** [comment]
@anilmaurya Hi, I know that.

But what I am confused is that I call `job.run` and `job.save`, then the job is persisted and the transaction is committed.

If we take active_record as an example, the `after_commit` will fired if `save` method is called.

**Comment by anilmaurya** [comment]
@lonre AASM does not observe your object, once you fire `job.run` AASM will fire `run` event and related callbacks. `job` status will be changed from 'sleeping'  to `running` . After this AASM does not care what you do with `job` object.

AASM `after_commit` callback is not related to active_record `after_commit` callback in any way.

**Comment by alto** [comment]
@lonre: @anilmaurya is right. @scottjacobsen updated the README accordingly (in PR #284). Maybe the name `after_commit` is too confusing, but it has absolutely nothing to do with _ActiveRecord_ `after_commit` hooks.

**Comment by lonre** [comment]
Yes, some people thought it is like ActiveRecord's `after_commit`.

Thanks @alto
