### ISSUE TITLE
Delayed Job(or other job app) + aasm - transitions not working

### ISSUE THREAD

**Issue by krim** [aasm/aasm#286]
Hello.
I'm want to use aasm with delayed job. When i create events, such as:
```
aasm column: :state, enum: true do
    state :created, initial: true
    state :in_progress,         after_enter: :check_account
    state :done
    state :refuse

    event :progress do
      transitions from: :created, to: :in_progress
    end

    event :check_game_account do
      transitions from: :in_progress, to: :done, guard: :check_account_exist?
      transitions from: :in_progress, to: :refuse
    end

private
def check_account_exist?
.....
end
```

And then i:
```
profile = Profile.new ....
profile.delay.progress
```
At result i will have state == "in_progress"
If i start 'progress' without delay i will have state 'refuse' or 'done'

**Comment by anilmaurya** [comment]
@krim Did you fixed this issue ? If you can mention what was actual problem and how did you solve it then it will help others programmers if they stuck at some thing like this.
