### ISSUE TITLE
whiny_transitions conflict with aasm.attribute_name

### ISSUE THREAD

**Issue by grgr** [aasm/aasm#287]
rewrite spec/models/silencer.rbin specs of aasm-4.5.0 like:

class Silencer
  include AASM

  aasm.attribute_name :state

  aasm :whiny_transitions => false do
    state :silent, :initial => true
    ....

and specs will fail with:
rspec ./spec/unit/transition_spec.rb:16 # transitions should not raise an exception when not whiny
rspec ./spec/unit/transition_spec.rb:22 # transitions should not raise an exception when superclass not whiny
rspec ./spec/unit/transition_spec.rb:44 # transitions should not call the block when failure

I had struggeled some time with this issue in a project.

Luckily, removing the line 'aasm.attribute_name :state' solves the problem.

**Comment by maokomioko** [comment]
Can confirm this (encountered just today), but on the second thought pointing attribute_name to the state is explicit. :)

**Comment by alto** [comment]
Interesting case. Will investigate.

**Comment by alto** [comment]
@grgr @maokomioko  Released version `4.5.1` fixing this bug. Thanks for pointing it out!
