### ISSUE TITLE
Proc with optional argument not work with guards

### ISSUE THREAD

**Issue by lingceng** [aasm/aasm#293]
Hi. I'm using Rails4.2 and aasm4.5

    event :check_step, after: :_done_tech do
      transitions from: :step_end, to: :step_done,
        guard: Proc.new {|options={}| options[:qualify_status]  == Technology::OK }
      transitions from: :step_end, to: :at_step
    end

When I run folowing test. I it will fail.

    context "when check passed" do
      it {
        order.check_step(qualify_status: Technology::OK, tester_id: worker.id)

        expect(order.aasm.current_state).to eq :step_done
        expect(order.current_technology.reload.qualify_status).to eq Technology::OK
      }
    end

**After some debug. I find the `options` will always be `{}`.
I find the problem may be the arity check in following code.**

    # lib/aasm/core/transition.rb#53
    case code
    when Symbol, String
      arity = record.send(:method, code.to_sym).arity
      arity == 0 ? record.send(code) : record.send(code, *args)
    when Proc
      code.arity == 0 ? record.instance_exec(&code) : record.instance_exec(*args, &code)

    # My proc arity is 0
    puts Proc.new {|options={}| options[:qualify_status]  == Technology::OK }.arity
    # => 0

**So I change the proc to lamda. The test passed.**

    lamba {|options={}| options[:qualify_status]  == Technology::OK }.arity
    # => 1

[arity acts differently in proc and lamda](http://ruby-doc.org/core-2.2.3/Proc.html#method-i-arity)

So it seems not a bug.
But demos in README uses Proc. It may mislead guys.
**Is it better to change the demos as following?**

     transitions :from => :sleeping, :to => :running, :after => lambda {|*args| set_process(*args) }

**Comment by alto** [comment]
@lingceng Wow, interesting case. I will have a look.

**Comment by alto** [comment]
@lingceng Could you take a look at the current _master_ version (at least with commit https://github.com/aasm/aasm/commit/6e97e794198447bb8d29bb1d6ed1c38afc7dc440) and try it out? If your issue is fixed I will release a new (patch) version.

**Comment by lingceng** [comment]
@ato Of course! A minute please.

**Comment by lingceng** [comment]
@ato Yes! The fix woks. :+1:

**Comment by alto** [comment]
@lingceng Great. I just released version `4.5.2` including the fix. Thanks for your help!
