### ISSUE TITLE
duplicate global callbacks caused by `after_all_transitions`

### ISSUE THREAD

**Issue by lingceng** [aasm/aasm#297]
#### Base code
Using aasm4.5.0, rails4.2.0

    class Job
      include AASM

      aasm do
        state :sleeping, :initial => true, :before_enter => :do_something
        state :running

        after_all_transitions :log_status_change

        event :run, :after => :notify_somebody do
          before do
            log('Preparing to run')
          end

          transitions :from => :sleeping, :to => :running, :after => Proc.new {|*args| set_process(*args) }
        end
      end

      def log_status_change
        puts "changing from #{aasm.from_state} to #{aasm.to_state} (event: #{aasm.current_event})"
      end
    end

#### Problem
I have added a puts at lib/aasm/base.rb#112

    def after_all_transitions(*callbacks, &block)
      puts '---> add after all transaction'
      @state_machine.add_global_callbacks(:after_all_transitions, *callbacks, &block)
    end

The '---> add after all transaction' will printed when I change some code in the
Job model and rails auto reload Job model.
And when I call `job.run!`. I will get two line of log puts

    changing from ...
    changing from ...

#### Analysis
I checked the `add_global_callbacks` method.
`@global_callbacks[:after_all_transitions]` get values as: `[:log_status_change, :log_status_change]`

    def add_global_callbacks(name, *callbacks, &block)
      @global_callbacks[name] ||= []
      callbacks.each do |callback|
        @global_callbacks[name] << callback
      end
      @global_callbacks[name] << block if block
    end

So I think it is a bug of `after_all_transitions`.

@alto

**Comment by alto** [comment]
@lingceng Hmm, I can't reproduce that issue. When does `@global_callbacks[:after_all_transitions]` get values as `[:log_status_change, :log_status_change]`?

**Comment by lingceng** [comment]
@alto 

I should give more details.

First, I'm in the development env. 
I triggered the **job.run()** when I clicked a button on my page.

Then, I add a line in the Job model. eg.

```ruby
class Job
  include AASM
  # Add a new line to make Job object reload in development env
  puts 'hello'
   
  aasm do
  ....
  end
end
```

After adding the line, I triggered the **job.run()** again. 
I got two lines of log

      puts "changing from..."
      puts "changing from..."

The `@global_callbacks[:after_all_transitions]` get values as: `[:log_status_change, :log_status_change]`

**Comment by andreazaupa** [comment]
I've a similar problem, 
aasm (4.7.0)

Callback method configured with after_all_transitions is called multiple time (maybe one time for every transitions defined).

**Comment by lingceng** [comment]
@alto I created a pull request to fix this problem. Please have a look.

**Comment by ethankang** [comment]
@alto, seems like in rails development env, model reloading will causes the aasm block to re-run, and global callbacks will be re-added.

**Comment by ilp416** [comment]
Thank you. Had this trouble in Rails 3 dev, only call aasm methods from controller.
After update all works right.

**Comment by timdavies** [comment]
This is still an issue if you use `after_all_transitions` with a block. For example:

```
class Foo
  include AASM

  aasm do
    state :sleeping, initial: true
    state :running

    after_all_transitions do
      puts "changing from #{aasm.from_state} to #{aasm.to_state} (event: #{aasm.current_event})"
    end

    event :run do
      before do
        puts 'Preparing to run'
      end

      transitions from: :sleeping, to: :running
    end
  end
end
```

Output:
```[1] pry(main)> Foo.new.run
Preparing to run
changing from sleeping to running (event: run)
=> true
[2] pry(main)> Foo.new.run
Preparing to run
changing from sleeping to running (event: run)
=> true
[3] pry(main)> reload!
Reloading...
^[[A=> true
[4] pry(main)> Foo.new.run
Preparing to run
changing from sleeping to running (event: run)
changing from sleeping to running (event: run)
=> true
[5] pry(main)> reload!
Reloading...
=> true
[6] pry(main)> Foo.new.run
Preparing to run
changing from sleeping to running (event: run)
changing from sleeping to running (event: run)
changing from sleeping to running (event: run)
=> true```

**Comment by rohitpal** [comment]
Even I am getting same issue with version 5.0.6. Is there any solution around it?

**Comment by matthee** [comment]
> This is still an issue if you use `after_all_transitions` with a block. For example:

Can confirm. This is still an issue with AASM version 5.5.0

**Comment by matthee** [comment]
> Is there any solution around it?

I've mitigated this issue by defining a method and using the symbol syntax instead. This should do the trick:

```ruby
aasm do
  after_all_transitions :track_state_change

  # Add states and events 
end

def track_state_change
  # Do your tracking here
end
