### ISSUE TITLE
after not woring when initial

### ISSUE THREAD

**Issue by towonzhou** [aasm/aasm#301]
```
state :new, initial: true, after: :some_new
event :confirm do
  transitions from: :new, to: :confirmed, after: :some_confirm
end
```
some_new is not work.   but some_confirm is work, why?

**Comment by lingceng** [comment]
@towonzhou No *after* callback exits for state. You can use *before_exit* or something similar.

**Comment by towonzhou** [comment]
@lingceng ok thanks

**Comment by alto** [comment]
@lingceng Right. Thanks for helping out!
