### ISSUE TITLE
How would this work with a json column using postgres?

### ISSUE THREAD

**Issue by mmahalwy** [aasm/aasm#306]
Instead of having individual fields on my model, I want to create a json column named `state` that may or may not contain certain keys.

How would this work (and perhaps if there is a good example) with aasm?

**Comment by alto** [comment]
@mmahalwy I'm not sure I understand what you are trying to achieve. Normally you would have a `state` column of type `string`, which can take any of your defined states (as strings). Do you want to store it as hash instead?

**Comment by mmahalwy** [comment]
@alto yes that's correct. For example, I have column with type JSON (utilizing Postgres' JSON column), I'd like to store multiple states on this column rather than individual columns for each type.

For example:
`state: {}`
On task in progress but on hold
`state: {in_progress: true, on_hold: true}`, and once the task is resolved, `state: {in_progress: true, on_hold: false}`

Does that help?

**Comment by alto** [comment]
@mmahalwy Yep, that helps. Unfortunately it's not supported by _AASM_. But I'm happy to take a pull request for it!
