### ISSUE TITLE
How can I test after_commit with none AR class?

### ISSUE THREAD

**Issue by alovak** [aasm/aasm#310]
Hi!

I have created a ruby class in order to test aasm states without need to deal with validations, etc.

Here it is:

```
class ChargeStatesTest
  include Charge::States

  attr_accessor :state, :captured_amount, :amount #...
end
```

In Charge::States I want to create async job for notification:

```
class Charge
  module States
    included do
      include AASM

      aasm column: :state do
        state :pending, :initial => true
        state :captured
        state :authorized
    
        event :capture, after: :create_notification do
          transitions :from => [:pending, :authorized], :to => :captured, after: :set_captured_amount
        end
        # ...

       def create_notification
         ChargeCapturedWorker.perform_async("something")
       end
    end
  end
end
```

with ```event after: ...``` async job can use record data before it was committed in DB (for example with 'pending' state). but with ```after_commit``` I can't use my plain ruby class to test state machine as it does not have any commit/transaction functionality.

Is there any way to create async task without explicitly using ```after_commit``` so it will work like ```after_commit``` when it's AR class and like ```after``` when it's plain ruby class?

**Comment by alto** [comment]
@alovak No, _AASM_ doesn't provide this functionality. You could check – when including `Charge::States` –, whether the base class is an _ActiveRecord_ model (and use `after_commit`) or not (and use `after`).
