### ISSUE TITLE
'after_commit' on event not firing after record is saved and committed

### ISSUE THREAD

**Issue by chinshr** [aasm/aasm#313]
When I am saving an instance after I changed the state with event (without bang), I am not receiving an `after_commit` callback, if I do the same with the bang, it works. Example:

```ruby
class Job < ActiveRecord::Base
  include AASM
  aasm column: 'aasm_state' do
    state :started, initial: true
    state :stopping

    event :stop, :after_commit => :after_commit_event_stop do
      transitions :from => :started, :to => :stopping
    end
  ...
  end

  def after_commit_event_stop
    puts "Not firing!"
  end
end

#  Create and stop a job
@job = Job.create
@job.event = :stop
@job.save
# Notice: after_commit_event_stop is not firing
```

Note: aasm, "~> 4.7"

**Comment by anilmaurya** [comment]
Hi @chinshr ,

This is the desired behaviour, please see https://github.com/aasm/aasm/issues/285

And read https://github.com/aasm/aasm#transaction-support

**Comment by chinshr** [comment]
That's very unfortunate as it makes the app logic a whole lot more complicated. I will have to use 'after' callback and observe the state transition on after commit to start a background job that I cannot launch unless the object is committed.

While I did not see an explanation in thread #285 for this behavior, I really appreciate your quick response!

**Comment by alto** [comment]
@chinshr The only explanation is that it has nothing to do with _ActiveRecord_ `after_commit` hooks. It only shares the name, not the behaviour. It's basically a _do this –for the currently triggered event– if and when the change has been committed to the database_. Saying this, it's totally event-based. A pure _ActiveRecord_ `save` (including all manual changes you did) is not going through any other _AASM_ callbacks either. An event trigger without `!` (bang) fires all callbacks that are not related to persisting the state change, as it doesn't persist the state.

**Comment by alto** [comment]
@chinshr Please have a look at #298. Let's continue to talk there.

**Comment by chinshr** [comment]
Yes, #298 addresses my issue.
