### ISSUE TITLE
rails g aasm doesn't works

### ISSUE THREAD

**Issue by betomoretti** [aasm/aasm#328]
Runing in console:
`rails generate aasm goal`
Could not find generator 'aasm'. Maybe you meant 'task' or 'assets' or 'controller'
`rails generate --help`
...
AASM:
  a_a_s_m:a_a_s_m
ActiveRecord:
  active_record:a_a_s_m
Mongoid:
  mongoid:a_a_s_m
...

Rails version: rails-4.2.2
Ruby version: ruby 2.2.1p85

**Comment by alto** [comment]
Hi @betomoretti 

Which version of _AASM_ are you using?

**Comment by betomoretti** [comment]
Hi @alto 

aasm-4.8.0

**Comment by alto** [comment]
@anilmaurya Do you have time to take a look at this? I can replicate what @betomoretti is saying.

**Comment by anilmaurya** [comment]
Ok, I will check this and fix it ASAP.

**Comment by alto** [comment]
@anilmaurya Great, thanks a lot!

**Comment by alto** [comment]
I just released version `4.9.0` including the change.
