### ISSUE TITLE
Is it possible to use a different aasm 'column' for ruby classes?

### ISSUE THREAD

**Issue by bahbbc** [aasm/aasm#331]
If I correctly understood the docs, if you are using ActiveRecord you can create a migration and change the default column from aasm. 

```ruby
include AASM

  aasm :column => :another_name do
    state :process, initial: true
    state :approve
    state :refuse
  end
```

But is it possible to use an attribute from a ruby class as well? using the `column` I wasn't able to do so. As a workaround I used some  `before_all_events` and `after_all_events` to set the current state machine in the attribute that I wanted, but this doesn't work for the initial state, no matter which callbacks I use. Is there a solution for it?

```ruby
aasm do
  state :preparation, initial: true
  state :sent_to_analysis
  state :end_integration

  before_all_events :get_status
  after_all_events :set_status

  event :send_to_analysis do
    transitions from: :preparation, to: :sent_to_analysis
  end

  event :end_integration do
    transitions from: :sent_to_analysis, to: :end_integration
  end
end

private
def get_status
  self.aasm.current_state = self.status
end

def set_status
  self.status = self.aasm.current_state
end
```

**Comment by alto** [comment]
@bahbbc You should be able to use the state callback `:after_enter` for this, which is called (besides `:before_enter`) on object initialisation. Let me know if that works.

**Comment by bahbbc** [comment]
@alto I already tried that... If I do it like this:

```ruby
state :preparation, initial: true, after_enter: :set_status
```

The set_status is never called on initialization.

**Comment by bahbbc** [comment]
I already understand what is happening! I my specs I only initialize the object and expected to have the status already settled. 

```ruby
it 'starts with status preparation' do
  subject = described_class.new

  expect(subject.status).to eql(:preparation)
end
```

But it only works if I call the aasm state... For example, if I do `aasm.current_state` in the spec it works. I though that the initial state and it's callbacks would be initialized with the object, but it looks like they do only if I verify the it's state.

**Comment by pirj** [comment]
Will that work for you?

```
class A
  include AASM

  aasm do
    state :preparation, initial: true
    state :sent_to_analysis
    state :end_integration
  end

  def status
    aasm.current_state
  end

  def status=(status)
    aasm.current_state = status
  end
end

a = A.new
a.status # => :preparation
a.status = :sent_to_analysis
a.status # => :sent_to_analysis
a.aasm.current_state  # => :sent_to_analysis
```

**Comment by t3hk0d3** [comment]
@bahbbc 
Just override these methods - `aasm_read_state`, `aasm_write_state`, `aasm_write_state_without_persistence`

Example:

```ruby
      def aasm_read_state(_name = :default)
        subscription.state.try(:to_sym).presence || self.class.aasm.initial_state
      end

      def aasm_write_state(new_state, _name = :default)
        subscription.update(state: new_state.to_s)
      end

      def aasm_write_state_without_persistence(new_state, _name = :default)
        subscription.state = new_state.to_s
      end
```

**Comment by bahbbc** [comment]
My solution was like @pirj suggested, since the object with aasm gem does not associate the states to an attribute. I made the initialization by myself, like this, the spec that I mentioned before will work.

I made it like that:
```ruby
class A
  include AASM
  
  def inititialize
    initialize_status
  end

  aasm do
    state :preparation, initial: true
    state :sent_to_analysis
    state :ended_integration

    before_all_events :set_current_state
    after_all_events :set_status

     event :prepare do
       transitions from: :sent_to_analysis, to: :preparation
     end

     event :send_to_analysis do
       transitions from: :preparation, to: :sent_to_analysis
     end

     event :end_integration do
       transitions from: :sent_to_analysis, to: :ended_integration
     end
  end

  private

  def set_current_state
    aasm.current_state = status.to_sym
  end

  def set_status
    self.status = aasm.current_state
  end

  def initialize_status
    self.status ||= aasm.current_state
  end
end
```
@t3hk0d3 I am not sure if your suggestion solves the initialization problem.

**Comment by pirj** [comment]
@bahbbc , cool that it worked! Do you mind closing the issue then?
