### ISSUE TITLE
Mongoid: has_many association _ids helper raising error

### ISSUE THREAD

**Issue by Shwetakale** [aasm/aasm#332]
Consider following association

    class Baby
      include Mongoid::Document
      include AASM

      belongs_to :user 

      aasm :column =>'status' do
        state :active, :initial => true
      end
    end

    class User
      include Mongoid::Document
      include AASM

       has_many :babies
    end

when we use has_many association with mongoid it gives baby_ids helper method.

When I am doing following 
    
    User.last.babies

It's working fine, But when I try to use helper method

    User.last.baby_ids

It's giving me following error

    ActiveModel::MissingAttributeError: Missing attribute: 'status'.
    from .rvm/gems/ruby-2.2.2@ficare/gems/mongoid-4.0.2/lib/mongoid/attributes.rb:98:in `read_attribute'
    from .rvm/gems/ruby-2.2.2@ficare/gems/mongoid-4.0.2/lib/mongoid/changeable.rb:232:in     `attribute_will_change!'
    from.rvm/gems/ruby-2.2.2@ficare/gems/mongoid-4.0.2/lib/mongoid/attributes.rb:177:in `block in write_attribute'
    from .rvm/gems/ruby-2.2.2@ficare/gems/mongoid-4.0.2/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
    from .rvm/gems/ruby-2.2.2@ficare/gems/mongoid-4.0.2/lib/mongoid/attributes.rb:171:in `write_attribute'
    from .rvm/gems/ruby-2.2.2@ficare/gems/aasm-4.1.1/lib/aasm/persistence/mongoid_persistence.rb:100:in `aasm_write_state_without_persistence'

As in mongoid we only have ```ids``` in ```attributes```

Is this intended behavior or we need to handle this in mongoid?

**Comment by Shwetakale** [comment]
I tried on latest version still facing same issue.

**Comment by alto** [comment]
I just released version `4.10.0` including the changes from #333.
