### ISSUE TITLE
[Feature Request] Add Appraisal (https://github.com/thoughtbot/appraisal)

### ISSUE THREAD

**Issue by anilmaurya** [aasm/aasm#334]
I found it difficult to test aasm for different versions of dependencies.

To run specs for different gemfile on local machine I copied respective gemfile to root Gemfile, did bundle install and then run specs. I had to repeat these steps for all gemfiles for which I want to run my specs.

I think adding `appraisal` gem will simplify this. If you know of any better way than please let me know.

**Comment by alto** [comment]
@anilmaurya Closing this issue in favour or the pull-request #342
