### ISSUE TITLE
Is aasm thread safe in multi tenant Rails 4.2 app?

### ISSUE THREAD

**Issue by emclab** [aasm/aasm#345]
Is aasm thread safe by default in multi tenant Rails 4.2 app? We are currently using geekq/workflow and not sure if it is thread safe. Our app is moving to serve multi tenant.

**Comment by emclab** [comment]
geekq/workflow is not thread safe in multi tenant app. user who logs in late overwrite previous user's workflow spec. There is only one workflow spec can be defined for one running app.

**Comment by emclab** [comment]
Is workflow spec defined in aasm by class method or instance method?

**Comment by pirj** [comment]
Can you please describe your use in more detail?
What do you mean by multi-tenant and thread safe exactly? What kind of failure scenarios are you experiencing with `workflow` and are trying to avoid?
Mind providing some scrambled failing code in isolation from the rest of your application like in [this example](https://gist.github.com/pirj/511e7ac40ced8c93b843)?

**Comment by emclab** [comment]
Probably multi state machines in one class better describe what we are looking for. We are looking for workflow with ability to handle multi state machines (workflows) for on class and event is applied with state machine name. According to the menu, aasm does support multi state machine for one class.
