### ISSUE TITLE
Warning when specifing states at ActiveRecord enum

### ISSUE THREAD

**Issue by leonelgalan** [aasm/aasm#347]
As @pirj [pointed out](https://github.com/aasm/aasm/pull/340#issuecomment-205490897), this is a common practice, detailed on the [README](https://github.com/aasm/aasm#activerecord-enums):

```
ModelName: overriding method 'a?'!
ModelName: overriding method 'b?'!
```

```ruby
enum a_status: {
  a: 0,
  b: 1
}

aasm column: a_status do
  state :a
  state :b 
}
```

**Expected behavior** is for aasm to skip creating the "question marked" methods when they already exist, because `enum` created them.

**Comment by holyketzer** [comment]
+1 same issue.

Sorry but for which purpose these warnings are needed? I don't understand motivation of this change https://github.com/aasm/aasm/pull/340

**Comment by pirj** [comment]
@holyketzer, [this test](https://github.com/aasm/aasm/blob/master/spec/unit/override_warning_spec.rb) might give you an idea why this was needed. Long story short, if you have a state `valid`, or even `lock`, it breaks Rails validation and pessimistic locking; if you have a boolean column `assigned` and a state `assigned`, it might became a nightmare using question mark method.

**Comment by betoharres** [comment]
same here. +1
A warning that shouldn't be there?

**Comment by leonelgalan** [comment]
I'm not entirely sure how I missed this, but this was "fixed" on #346 and by setting `enum: true` as directed on the [README](https://github.com/aasm/aasm#activerecord-enums) the warning doesn't show. I have concerns with the solution but I'll post them on that PR's thread.

**Comment by jonbcampos** [comment]
@leonelgalan you mean that it was missed and the warning will be fixed in the next release or should already work like that?

I ask cause I have the enum: true already set and am still seeing the warning

**Comment by leonelgalan** [comment]
That's only because the PR I linked hasn't reach a released version, but it's fixed in the _master_ branch.

**Comment by jonbcampos** [comment]
@leonelgalan good to know, thank you
