### ISSUE TITLE
How to refer current instance in guard method?

### ISSUE THREAD

**Issue by emclab** [aasm/aasm#359]
How to refer current instance in guard method? 

The following seems not working:

     def cleaning_needed?
        return true if self.dog_walked
     end

In geekq/workflow, it allows a proc for a conditional event (with if) and it works well.

**Comment by t3hk0d3** [comment]
Strange, it works for me.

```ruby

class TestClass
  include AASM

  aasm do
    state :test, initial: true

    event :test do
      transitions from: :test, to: :test, guard: [:is_working?]
    end
  end

  def is_working?
    !self.procrastinating?
  end

  def procrastinating?
    puts "OMGWTF!"
    false
  end
end

obj = TestClass.new

obj.test!
```

**Comment by anilmaurya** [comment]
@emclab I checked on recent AASM release and its working as mentioned by @t3hk0d3 .

@t3hk0d3 Thank you for your help . ♡

I am closing this issue, @emclab feel free to reopen if you are still facing this issue.
