### ISSUE TITLE
Define multiple state only once

### ISSUE THREAD

**Issue by TangMonk** [aasm/aasm#360]
I am following Documentation:
![image](https://cloud.githubusercontent.com/assets/3498786/15090052/75c9d51e-1449-11e6-9080-f83dc728edc1.png)

My state:

```
aasm do
    state :unpaid, initial: true
    state :unused, :refunding, :refunded, :deleted, :finished

    event :pay do
      transitions from: :unpaid, to: :unused, after: after_pay
    end
  end
```

but actually throw me error: 

```
~/.rvm/gems/ruby-2.1.5/gems/aasm-4.5.1/lib/aasm/base.rb:66:in `state': wrong number of arguments (5 for 1..2) (ArgumentError)
```

**Comment by t3hk0d3** [comment]
Make sure you are using lastest version.
Documentation is made for ``4.10``, yours is ``4.5.1``

**Comment by TangMonk** [comment]
Sorry, my problem...
