### ISSUE TITLE
:before callback

### ISSUE THREAD

**Issue by dudo** [aasm/aasm#377]
`event :run, :before => :do_something`

That doesn't work... Seems I have to use `before_enter` on the actual state. Another gotcha is when running the before_enter method, if I have a `self.foo = 'bar'`, `foo` is not being set. I need to explicitly call `self.save`. I don't love that.

Thoughts?

**Comment by anuj-verma** [comment]
I have executed `event :run, :before => :do_something`. It works correctly in my case. You can write callbacks on both event and state. The only catch is how cleverly you use them. 
Can you please tell me what error you are getting ?

By writing `self.foo = 'bar'` in your callback method, you are only setting the value of foo. You have to explicitly save it.

**Comment by anilmaurya** [comment]
@dudo 

Event callbacks is working as expected (https://github.com/aasm/aasm/blob/master/spec/unit/callbacks_spec.rb#L73).

If you are doing `self.foo = 'bar'` in `before` callback and you `foo` to set after event transition then you call `run!`.  `run!` will call `save` on `self` therefore persisting your `before` callback changes.

If you want to update attributes in `after` callback than you can use [update](http://apidock.com/rails/ActiveRecord/Base/update/class) for ActiveRecord or [set](http://www.rubydoc.info/github/mongoid/mongoid/Mongoid%2FPersistable%2FSettable%3Aset)  for Mongoid.

@anuj-verma Thank you for your help. 

@dudo I am closing this issue, Let me know if you need any more clarification.
