### ISSUE TITLE
initial state will not fire before_enter, enter, or after_enter callbacks if database column has a default value.

### ISSUE THREAD

**Issue by JasonPoll** [aasm/aasm#381]
Possible bug? 

I think the _[Column name & migration](https://github.com/aasm/aasm#column-name--migration)_ and _[Callbacks](https://github.com/aasm/aasm#callbacks)_ sections of the documentation should explain that if the database colum which backs your ActiveRecord model's AASM column defines a default value at the database level, any AASM callbacks on the initial state will not be fired upon instantiation of the model.

Or the doco should strongly recommend against defining a default value at the database level when you create the migration because of the callback issue, as well as there being no checking that the initial state defined by the state machine and the database column are the same.  Additionally, setting the `:no_direct_assignment => true` attribute on the state machine doesn't appear to raise an error in this situation either. 

I have not looked through the AASM code, but the behavior seems to imply that AASM won't set the initial state if the model instance's state attribute already contains a non-nil value, and thereby before_enter/enter/after_enter state callbacks will not fire.

**Comment by matteeyah** [comment]
@alto @anilmaurya WDYT? I think this should at least be documented. I just ran into this, if it wasn't for this issue I would've spent hours of digging to find this out.

**Comment by anilmaurya** [comment]
Agreed @matteeyah , I will add this behaviour  to docs.
