### ISSUE TITLE
'rails generate aasm MODEL' broken

### ISSUE THREAD

**Issue by tamaloa** [aasm/aasm#382]
With current rails 4.2 and aasm 4.2.0 in a fresh application

    ~aasm_test$ rails generate aasm User
    Running via Spring preloader in process 23135
    Could not find generator 'aasm'. Maybe you meant 'task', 'assets' or 'job'
    Run `rails generate --help` for more options.

**Comment by anilmaurya** [comment]
Duplicate #328 

Can you test with version > `4.9.0`

**Comment by tamaloa** [comment]
Sorry, thought i had the most recent aasm version - newer one works :)
