### ISSUE TITLE
AASM don't pass arguments to guard

### ISSUE THREAD

**Issue by WaKeMaTTa** [aasm/aasm#391]
```ruby
class Character < ActiveRecord::Base
  include AASM

  aasm :located_in do
    state :home, initial: true
    state :school

    event :go_to_school do
        transitions from: :home, to: :school, guard: Proc.new { |*args| has_launch?(*args) }
      end
  end

  def has_launch?(meal)
     meal != nil
  end
end
```

```console
@jhon = Character.create(name: "Jhon")
@banana = Meal.where(name: "Banana")
@jhon.may_go_to_school?(@banana)
> false
```

Needs to be true, i inspected and i found AASM don't pass argument `@banana` to method `has_launch?`

**Comment by anilmaurya** [comment]
@WaKeMaTTa Can you check this on latest release i.e `4.11.0`. I checked on `4.11.0` and passing arguments to guards works for `may_*events` methods

**Comment by WaKeMaTTa** [comment]
@anilmaurya Ah! okey i was using `event` and `event!` methods.

**Comment by anilmaurya** [comment]
@WaKeMaTTa If its not issue anymore than can you close this issue ?
