### ISSUE TITLE
Strange error when switching statuses

### ISSUE THREAD

**Issue by nachootal** [aasm/aasm#402]
Hello,

in my rails app, I'm able to change the state as wished in two points of the app but in one, I'm not able to do so. I wonder why. The output of the server is the following:

`  
ProposalStage Load (0.5ms)  SELECT `proposal_stages`.* FROM `proposal_stages`  WHERE `proposal_stages`.`proposal_id` = 29 AND (`proposal_stages`.`flight_id` IS NOT NULL) AND (`proposal_stages`.`status` != 'not_sent') AND (`proposal_stages`.`status` != 'no_stock') AND (`proposal_stages`.`status` != 'rejected')
  Flight Load (0.4ms)  SELECT  `flights`.* FROM `flights`  WHERE `flights`.`id` = 92 LIMIT 1
   (0.2ms)  BEGIN
Proposals Accepted
   (0.2ms)  ROLLBACK
Completed 500 Internal Server Error in 13538ms

ActiveModel::MissingAttributeError (can't write unknown attribute `proposal_stage_id'):
  lib/api_jsons.rb:549:in `block (2 levels) in accept_transports'
  lib/api_jsons.rb:547:in `block in accept_transports'
  lib/api_jsons.rb:545:in `each'
  lib/api_jsons.rb:545:in `accept_transports'
  lib/api_jsons.rb:645:in `manage_proposals'
  app/controllers/apis_controller.rb:45:in `block (2 levels) in manage_proposals'
  app/controllers/apis_controller.rb:44:in `manage_proposals'
`

This attribute does not belong to the model I'm updating the status though it matches with the model name (ProposalStage).

I'm running rails 4.1.8 and ruby 2.3.0.p0

Where do you suggest I start looking?. I've found that this change of status is available on other part of the app with no error at all (as expected).

In case you'd need further information, I'm open to disclose it too.

Cheers

**Comment by anilmaurya** [comment]
@nachootal I think this error is not related to AASM.

may be something is wrong with your model relationship, like in this stackoverflow http://stackoverflow.com/q/20745049/1970061 question.

If you need assistance in resolving issue , please show related model and controller code.

**Comment by nachootal** [comment]
Totally right. Thank you very much @anilmaurya for your help. Didn't spot it at the first sight.

Best regards and thanks for this gem :)
