### ISSUE TITLE
Callbacks not called with enum column

### ISSUE THREAD

**Issue by mmahalwy** [aasm/aasm#407]
Code:

```
  enum state: { draft: 0, review: 1, approved: 2, in_progress: 3, completed: 4 }

  aasm column: :state do
    state :draft, initial: true, before_enter: :generate_invoice
    state :review, before_exit: :generate_invoice
    state :approved, after_enter: :generate_invoice
    state :in_progress
    state :completed
  end
```

When doing `Order.last.approved!`, I expect `generate_invoice` to be called but nothing. It is only called when I create an event. 

Two questions that relate to this:
1. Seems like enum methods are not being caught by aasm
2. Can I do `Order.last.update(state: :approved)` and it triggers with aasm?

**Comment by pirj** [comment]
1. Create an event called `approve` to transition to `approved` state, that adds a bit of readability to your code as well. No, enum methods are not being caught
2. No, aasm is reacting to events, not underlying state changes. That would induce an ambiguity of being unable to detect the previous state for all the supported persistence adapters.
3. `complted` in your code has a typo

**Comment by mmahalwy** [comment]
@pirj thanks! Makes sense!
