### ISSUE TITLE
Can be additional parameters passed to guard method

### ISSUE THREAD

**Issue by agm1988** [aasm/aasm#414]
So for example I wont to trigger some event and pass a user to it as an argument.
Can I allow this event only if for example user.admin? # => true ?

```
event :run do
  transitions :from => :idle, :to => :cleaning, :guard => Proc.new {|*args| verify_admin(*args) }
end

job = Job.new
job.run(nil, current_user)
or

job.may_run?(current_user) # => false if user.admin? false
```

**Comment by tedtoer** [comment]
@agm1988 Did you try it? I thing this is possible
A necessary functional is here https://github.com/aasm/aasm/blob/master/lib/aasm/core/transition.rb#L55

**Comment by cdesch** [comment]
This seems to work for me. I think this can be closed.

**Comment by anilmaurya** [comment]
Thanks @cdesch 
@agm1988 Please reopen if you are still facing any issue.

**Comment by aviisekh** [comment]
How do I find the permitted states for the user with different roles? Is there any way where I can pass the current parameter to the following method?

job.aasm.states("permitted": true)

**Comment by pjoshi-linkwok** [comment]
@aviisekh - Yes, its possible.

You can find states or events using
`job.aasm.states({permitted: true}, current_user).map(&:name)`
`job.aasm.events({permitted: true}, current_user).map(&:name)`

In Model, You can add guard on events or states using `Proc` or other method as below:
```
event :hod_approve, guards: Proc.new {|*args| args[0].has_role?('hod') } do
    transitions from: :pending, to: :hod_approved
end
```
