### ISSUE TITLE
How to get new value instead of old value in after functions?

### ISSUE THREAD

**Issue by FX-HAO** [aasm/aasm#415]
Let's say i have the following code:

      state :a, :b

      event :next do
        transitions :from => :a, :to => :b, :after => :after_callback
      end

      def after_callback
      	p state  # => Got `a` rather than `b`
      end

How to get `b` rather than `a`?

**Comment by tanner-rutgers** [comment]
@FX-HAO did you solve this? I also have the same issue

**Comment by FX-HAO** [comment]
Try `aasm.from_state` and `aasm.to_state`
