### ISSUE TITLE
Shortcut for timestamps

### ISSUE THREAD

**Issue by Drenmi** [aasm/aasm#418]
A common and recurring thing we do is implement callbacks for updating timestamps. How about an option for `state` that automatically updates the timestamp when the record enters that state?

```ruby
state :finished, timestamp: true
# Will look for an attribute `finished_at`
```

perhaps with an optional attribute name for flexibility:

```ruby
state :draft, timestamp: :drafted_at
```

WDYT?

**Comment by anilmaurya** [comment]
I liked optional attribute name flexibility.

Would like to have this feature in AASM, are you interested in sending a PR ?

**Comment by CapCap** [comment]
@anilmaurya am getting the same thing as #424

```
Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.
Installing aws-sdk-core 2.6.44
An error occurred while installing nokogiri (1.7.0.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.7.0.1'` succeeds before bundling.
```

**Comment by Drenmi** [comment]
@anilmaurya: I might be able to submit a PR, once I have some spare time. 😅 If anyone comes across this and wants to work on it, feel free. 😊

**Comment by anilmaurya** [comment]
@CapCap At first it look looks like `nokogiri 1.7.0.1` dependency on `ruby >= 2.1.0` may be the reason behind failing specs. I will debug further to solve it.
@Drenmi Looking forward for pull request 😊

**Comment by anilmaurya** [comment]
@Drenmi Just came across #427 , @CapCap is working on this.

**Comment by lichtamberg** [comment]
Can be closed after this was merged or?

**Comment by Drenmi** [comment]
@lichtamberg: The relevant PR (#427) is still open. I don't think anyone is working on it though. 🙂

**Comment by kbighorse** [comment]
Was the OP's mentioned optional attribute name for flexibility ever implemented?

`state :draft, timestamp: :drafted_at`
