### ISSUE TITLE
How to skip transactions with ActiveRecord persistence

### ISSUE THREAD

**Issue by erictrue** [aasm/aasm#431]
Our application performs a "create" operation which cannot be rolled back without side effects. Specifically, we call an external API to create an object in another system, then add the corresponding record in our database. If an exception is raised, the record is rolled back, but the object is not deleted.

Right now we are hacking around this by performing the operation in a `before_transaction` block, but it will be difficult to maintain going forward. Is there a way to skip transactions with ActiveRecord persistence? If not, could you add one?

**Comment by lichtamberg** [comment]
yeah I have the same problem, quite a showstopper for me at the moment... Did you found a better solution?
