### ISSUE TITLE
Possibility of a unique state at same time

### ISSUE THREAD

**Issue by brunowego** [aasm/aasm#435]
Maybe it is not the purpose of this library, but I have a very interesting case where a state must be unique, that is, no other registry can be in the same state at the same time.

Is it possible to do with some configuration? Thanks.

**Comment by brunowego** [comment]
Maybe a simple uniqueness validation in rails...

**Comment by reidmorrison** [comment]
If I understand the requirement correctly, you have a model that uses AASM and you need to be sure that only one persisted instance of that model is in a particular state at any time?

We have a similar need in Rocket Job for "singleton jobs" where two instances of a job cannot be processed at the same time. It uses a validation that checks if any other instance is already in the database in a conflicting state: https://github.com/rocketjob/rocketjob/blob/master/lib/rocket_job/plugins/singleton.rb

**Comment by brunowego** [comment]
Exactly what I want @reidmorrison. Thanks.
