### ISSUE TITLE
ArgumentError: wrong number of arguments when first argument is nil

### ISSUE THREAD

**Issue by werleo** [aasm/aasm#441]
When first argument to event is nil it is removed from argument list.
In consequence we get:

```
ArgumentError: wrong number of arguments (given 1, expected 2)
```

Test scenario:

https://github.com/werleo/aasm/commit/354e05f27f49ee15eaca1d8649b369b971d3e114

**Comment by lichtamberg** [comment]
I think i found the problem, working on a patch at the moment

**Comment by lichtamberg** [comment]
It looks like its this method definition which removes the first argument, because to_state is nil:

```ruby
#aasm/lib/aasm/core/event.rb @ line 44 AASM::Core::Event#may_fire?


    43: def may_fire?(obj, to_state=nil, *args)
 => 44:   binding.pry if args.size == 1
    45:     puts "#{caller[0]}\t#{args.to_s}" # debug
    46:   _fire(obj, {:test_only => true}, to_state, *args) # true indicates test firing
    47: end

[1] pry(#<AASM::Core::Event>)> to_state
=> nil
[2] pry(#<AASM::Core::Event>)> args
=> ["yuppi"]
```

Don't know how to refactor this though...

**Comment by anilmaurya** [comment]
@werleo Can you run your specs on master branch and let me know if this issue is resolved ?

**Comment by werleo** [comment]
@anilmaurya test is passing on master branch.
Thank you for fixing it.

Test is in PR https://github.com/aasm/aasm/pull/485/files
I made it by mistake so you may close it.

**Comment by anilmaurya** [comment]
I would like to merge #485 , can you rename `wrong_arguments_list` to  `guard_arguments_check` ?

**Comment by werleo** [comment]
Renamed.
