### ISSUE TITLE
Possibility to inform a phase

### ISSUE THREAD

**Issue by brunowego** [aasm/aasm#447]
I have a special case where I need separate in block with phases. The initial phase is the proposal and the last is negotiation. So, this is my business logic, I know, but I think this is good for another users who have large states.

```rb
aasm :state, phase: proposal do
   ...
end

aasm :state, phase: negotiation do
   ...
end
```

This is possible with some customization?

**Comment by brunowego** [comment]
The follow code solve my issue, by now.

```rb
aasm :state do
  state :initialised, before_enter: proc { |s| s.phase = :proposal }
  ...
end

aasm :state do
  state :started, before_enter: proc { |s| s.phase = :negotiation }
  ...
end
```

**Comment by lichtamberg** [comment]
Is this still open or can you close it?
