### ISSUE TITLE
success callback not being invoked

### ISSUE THREAD

**Issue by EdmundLeex** [aasm/aasm#448]
Here's what I have. And I have absolutely no idea how to replicate it.

```ruby
class RmaOrder < Order
  aasm column: :status do
    state S_NEW, initial: true
    state S_COMPLETE
    state S_CANCELLED

    after_all_events do
      save!
    end

    event :complete do
      transitions from: S_NEW, to: S_COMPLETE, guard: :ready_for_completion?

      success do
        # this is not running whatsoever
        set_totals
      end
    end
  end
```

And I have another class that is exactly the same (well, I literally copy pasted it), and it invokes the `success` just like it should.

State transitions successfully, `ready_for_completion?` returns `true`. If I switch to use `after` callback, it works.

Any idea?

**Comment by anilmaurya** [comment]
Hi @EdmundLeex,

Thank you for reporting issue but I am not able to reproduce this scenario.
Unless I reproduce this issue, I won't be able to solve it.

Can you give a spec where it happens OR dummy app where  I can reproduce this issue ?

Thanks

**Comment by EdmundLeex** [comment]
Hi @anilmaurya, I wasn't able to replicate this as I mentioned. One thing though is, my base class also implemented state machine if this might give any clue.

I had two classes that inherited from the same base class, with the exact same code when I was testing (copy pasted). But one of them just wasn't invoking the callback.

Now I have work around the problem using other callbacks.

**Comment by lichtamberg** [comment]
So is it good to close or? Or still open?

**Comment by adamniedzielski** [comment]
I managed to find a scenario where `success` callback is not being triggered consistently. It involves two threads that execute the same transition on two completely unrelated models. Here's the minimal script to reproduce it:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activerecord', '5.1.4'
  gem 'pg'
  gem 'aasm', '4.12.3'
end

require 'active_record'
require 'pg'
require 'aasm'

puts "AASM: #{AASM::VERSION}"

ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'aasm-success-callback')

if !ActiveRecord::Base.connection.table_exists? :documents
  ActiveRecord::Migration.create_table :documents do |t|
    t.string :aasm_state
  end
end

class Document < ActiveRecord::Base
  include AASM
  after_save :wait_a_bit

  aasm do
    state :initial, initial: true
    state :confirmed
    event :confirm do
      transitions from: :initial, to: :confirmed, success: :be_happy
      transitions from: :confirmed, to: :confirmed
    end
  end

  def be_happy
    puts "success callback"
  end

  def wait_a_bit
    sleep 1
  end
end

puts "test with one record transitioning at a time"

doc_one = Document.new
doc_one.confirm!

puts "test with two records"

doc_one = Document.new
doc_two = Document.new(aasm_state: "confirmed")

thread_one = Thread.new { doc_one.confirm! }
sleep 0.5
thread_two = Thread.new { doc_two.confirm! }

thread_one.join
thread_two.join
```

And the output from the execution:

```
AASM: 4.12.3
test with one record transitioning at a time
success callback
test with two records
```

When two records transition at the same time (for example two Sidekiq jobs being executed at the same time), the success callback is not being called. 

The reason for that is using `@valid_transitions` in `AASM::Core::Event`. The value is manipulated when the transition is fired (https://github.com/aasm/aasm/blob/97e1fa501d1ffcc58ef0b22e51c777b9bbceca08/lib/aasm/core/event.rb#L148) and then read when the callbacks are executed (https://github.com/aasm/aasm/blob/97e1fa501d1ffcc58ef0b22e51c777b9bbceca08/lib/aasm/core/event.rb#L80).

Unfortunately, instances of `AASM::Core::Event` are shared between ActiveRecord model instances so two model instances transitioning at the same time may lead to incorrect results.

**Comment by pedros007** [comment]
@EdmundLeex Are you using ActiveRecord? If so, try setting `whiny_persistence: true`:

```ruby
aasm column: :status , whiny_persistence: true do
  ...
end
```

I recently ran into a case where a few callbacks were not firing.  Turning on `whiny_persistence: true` helped me detect an `ActiveRecord::RecordInvalid` exception that was being gobbled up when I ran `my_model.some_transition!`.

**Comment by guewen** [comment]
Hi, we are investigating issues with `success` callbacks not being fired as well. 

`whiny_persistence` is indeed a good one to activate.

@adamniedzielski do you still have the issue you describe, or maybe did you found a work-around?

@anilmaurya what do you think of the thread-safe issue described by @adamniedzielski?

Thanks!

**Comment by guewen** [comment]
> Hi, we are investigating issues with `success` callbacks not being fired as well.
> 
> `whiny_persistence` is indeed a good one to activate.
> 
> @adamniedzielski do you still have the issue you describe, or maybe did you found a work-around?
> 
> @anilmaurya what do you think of the thread-safe issue described by @adamniedzielski?

Follow-up: for now, as a band-aid, we made the jobs using AASM transitions run sequentially, and we do no longer have issues with success callbacks not fired.

**Comment by adamniedzielski** [comment]
> do you still have the issue you describe, or maybe did you found a work-around?

@guewen it's been 4 years, I don't remember anymore 😅 in the meantime the company I was working for got shut down by the main investor (✊ ✊ ✊ ) and I don't have access to the git history anymore. All gone, sold out for peanuts 😭 😭 😭

**Comment by guewen** [comment]
@adamniedzielski 😱
Anyway, many thanks for documenting the issue back then, you spared me a lot of hours if not days of headaches 🤩
