### ISSUE TITLE
Remove the warning for multiple state machines?

### ISSUE THREAD

**Issue by gsdean** [aasm/aasm#451]
> Final note: Support for multiple state machines per class is a pretty new feature (since version 4.3), so please bear with us in case it doesn't work as expected.

It's [two years old](https://github.com/aasm/aasm/blame/master/README.md#L459) and may be preventing people from adopting this feature.

Is there already a plan to remove it?

**Comment by anilmaurya** [comment]
@gsdean Thank you for reporting 👍
