### ISSUE TITLE
Apply namespace to event methods as well?

### ISSUE THREAD

**Issue by Aryk** [aasm/aasm#469]
The old state_machine gem did this and was curious why this gem doesn't.

I noticed in the specs for example, that even when a namespace is defined, it will apply to the reader methods but not to the 'event' methods. Any reason it does not apply to event methods.

So if the namespace is 'car' and the states are 'sold' and 'unsold', you would have an event 'sell', so:

```ruby
object.car_sold?
object.sell_car!
```

thoughts? Would you guys accept a PR if it was added without any side-effects to previous versions?

**Comment by anilmaurya** [comment]
Thanks @Aryk , I think extra configuration is not required.

If `:namespace`  is set to true then defining namespace for event method is fine, I think.

**Comment by Aryk** [comment]
The problem is, it is a breaking change. Are you guys ok with introducing this change?

Or should we alias the old version of the methods to ensure backwards compatibility?

**Comment by Aryk** [comment]
Hey guys, any updates on this? How do you want to proceed. 

This [commit](https://github.com/Aryk/aasm/commit/4d3f14576ecdf78a38caf64a360a0f6acb07911d) does not break it, but I'm more than happy to do the "If :namespace is set to true then defining namespace for event method is fine, I think." solution if you guys are ok with it.

Just let me know.

**Comment by anilmaurya** [comment]
Hi @Aryk , I do not want to break old version. Adding alias methods will do the job.

I am not in favor of  `:namespace_event_methods` because there will be very less chances when namespace is only required for `events` and not for `states`.

Thank you for contributing , I appreciate your help .

**Comment by Aryk** [comment]
Ok, I will implement this with aliases then. PR coming soon.

**Comment by anilmaurya** [comment]
Fixed with https://github.com/aasm/aasm/pull/476
