### ISSUE TITLE
Adding state change log functionality to AASM

### ISSUE THREAD

**Issue by dubroe** [aasm/aasm#490]
Hello. At my company we're using a forked version of AASM where we've added functionality to automatically store a log of every state change in a `aasm_state_change_logs` table. The table contains values such as `from_state`, `to_state`, `transition_name`, timestamps, etc.

Have you ever considered adding this functionality? Would you be interested in me preparing a pull request to introduce it?

Thanks!

~Elan

**Comment by anilmaurya** [comment]
Hi @dubroe ,

Thank you for your interest in contributing to AASM. I think https://github.com/airblade/paper_trail gem implement this functionality.

Let me know if you think otherwise.

**Comment by dubroe** [comment]
Hi Anil. Thanks very much for responding. Your suggestion to use PaperTrail is interesting. I think we could get it to work, but it would take quite a bit of configuration, such as setting it to only make versions for state changes and using the `meta` option to store the non-model values such as the transition name.

Also with PaperTrail it stores the changes as YAML, so we'd have to write custom code to support the queries we make in our system such as `widget.aasm_state_change_logs.where(from_state: %w(a b c), to_state: %w(d e f))`. The implementation for this using PaperTrail would likely be more complex.

Using the implementation in our fork is nice and elegant. We simply added an optional parameter when we call the `aasm` method for when we want to track state changes:
```
aasm column: :state, log_state_changes: true do
   state :a
   event :x
  ...
end
```

And then once we do this, AASM takes care of the rest, and we have the ability to make queries on our widgets like the one above.

The only other functionality we added is the ability to set `custom_state_change_log_data` on the `aasm` object in case we want to store additional data such as `user_id`, `comment`, etc. So I guess this is analogous to PaperTrail's `whodunnit` and `meta` functionality.

I'm curious to know what you think about this. Do you think tracking the state changes should be considered out of scope for AASM? Or do you think some of the users would find it useful?

**Comment by anilmaurya** [comment]
@dubroe do you have plan in mind to support `Mongoid` as well ?

**Comment by dubroe** [comment]
@anilmaurya we haven't done this yet, but we could definitely look into it if that was a prerequisite to get this feature merged in. I take it you want all of the features to be supported by both ActiveRecord and Mongoid?

**Comment by anilmaurya** [comment]
That's right, I want all the feature to be supported by ActiveRecord and Mongoid.

**Comment by dubroe** [comment]
Ok fair enough. I'll get to work on that and send you the PR when it's ready?

**Comment by anilmaurya** [comment]
Would you mind sharing your plan before writing PR ?

**Comment by dubroe** [comment]
Sure. I can even share the diff for what we're currently using: https://github.com/aasm/aasm/compare/master...financeit:master

What we've added:
1. A `log_state_changes` config option to enable state change logging. This adds the `has_many` relationship to the model and the functionality to store the state changes in the `aasm_state_change_logs` table.

2. An `attr_accessor` called `custom_state_change_log_data` which can set set on an `aasm` instance to set extra data you want stored for a transition aside from `from_state`, `to_state`, `transition_event` and timestamps. We use this by setting this data in our `aasm_event_fired` methods.

3. Creation of the `aasm_state_change_logs` table in the generator.

What we would still need to do:
1. Add Mongoid support.
2. Make the AASM::StateChangeLog class generic instead of an ActiveRecord subclass.
3. Write / fix tests

**Comment by mbramson** [comment]
So just as a thought about we have recently handled this, we implemented this at the database layer, which is where I think it belongs honestly. It's just a per row trigger on the table that contains state that also saves to an audit table every time the table is changed.

There are some huge benefits to this approach. You don't have to ever worry about one portion of the application logic succeeding (state change) and another failing (logging) due to any intermittent database issues, as both changes occur or none of them do. This ensures that you can 100% rely on your audit table to actually reflect every single thing that was done to the state table. It's also quicker, as you don't have to make separate calls to the database.

**Comment by anilmaurya** [comment]
@mbramson I see, using database approach makes audit table 100% reliable. I am interested in your database script for audit table .

If your solution is generic then sharing it on AASM readme will help others, I think.

**Comment by BKSpurgeon** [comment]
hi there, I'm facing the same issue: wanting to keep track of when the state changes occurred, and what they transitioned to (and from where).

@mbramson - thank you for your comment do you have more information on the: (i) recording and managing of states?

@dubroe would be interested to hear your solution, and how it differs from @mbramson's ideas.

**Comment by nitsujri** [comment]
Circling back to describe the solution we used:

We ended up using the `paper_trail` gem, but specifically creating a [separate version model & table](https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes) for the aasm model.

Deciding factors:
- The version is isolated against all the noise of the rest of versions thus allows it to become a first class citizen/tracking object.
- Get papertrail [version/change querying](https://github.com/paper-trail-gem/paper_trail#3b-navigating-versions)
- We also wanted to only track transitions and realized if there were other versions being created other than event transitions, we would immediately know we had leaky mutations.

The code simply becomes

```
  aasm do
    before_all_events :before_all_events
  end

  # Later in file
  def before_all_events
    self.paper_trail_event = aasm.current_event
  end
```

Just be sure to enable [--with-changes](https://github.com/paper-trail-gem/paper_trail#5c-generators).

**Comment by anilmaurya** [comment]
Hi @nitsujri ,
Thank you for sharing your solution. If you got little more time, would you mind creating sample application which showcase your solution.
I would like to add all available solution in AASM docs.

**Comment by nitsujri** [comment]
@anilmaurya here's a ultra quick & dirty example i whipped up for you: https://github.com/nitsujri/aasm-papertrail-example

thoughts?

Perhaps we can close this thread.

**Comment by anilmaurya** [comment]
@nitsujri Thank you. 🏆
I will update Docs and then close this issue.

**Comment by anilmaurya** [comment]
@nitsujri Added your example in Readme, closing this issue now.
