### ISSUE TITLE
fire event dynamic

### ISSUE THREAD

**Issue by slayer** [aasm/aasm#492]
Hi

It will be super to avoid code like this
```
user.send("#{event}!")
```

We need method like this:
```
user.aasm.fire!(event)
```

**Comment by anilmaurya** [comment]
@slayer I agree, `user.aasm.fire!(event)` looks neat.

I appreciate  pull request for the same

**Comment by slayer** [comment]
https://github.com/aasm/aasm/pull/494

**Comment by anilmaurya** [comment]
Pull request merged, Thank you for contributing

**Comment by pjmartorell** [comment]
This implementation has an error when you pass an unknown event to `fire!` or `fire`, i.e. `Model.aasm.fire!(:whatever)`

It raises a: `NoMethodError (undefined method `fire_callbacks' for nil:NilClass)`
Additionally it triggers before callbacks. To be consistent it should return an exception or some kind of error like "Unknown event", and then it should trigger before callbacks.

**Comment by slayer** [comment]
Hi @pjmartorell 
Yes, I agree with you, throw exception before callbacks will be really more consistent.
