### ISSUE TITLE
Pass a parameter to aasm event

### ISSUE THREAD

**Issue by flyingboy007** [aasm/aasm#506]
I am using aasm statemachine. I have the below event. What this does is changes the state from `order_created` to `payment_response_received`. So after changing this I want to call a method `verify_payment_response(data)`. 
I can make this state change by calling `@booking.move_to_payment_response_received!` , but how can I pass parameters for use in the after callback?

    event :move_to_payment_response_received do
      after_commit do
             self.verify_payment_response(data) #How can I pass this data param from my controller
      end
      transitions from: :order_created, to: :payment_response_received
    end

**Comment by anuj-verma** [comment]
Hi @flyingboy007 ,
You can do it like:
```
event :move_to_payment_response_received do
  transitions from: :order_created, to: :payment_response_received, :after => Proc.new {|*args| self.verify_payment_response(data)  }
end
```
Then from controller call the event like:
```
@booking.move_to_payment_response_received!(:payment_response_received, data)
```
When passing arguments to a state transition, the first argument must be the desired end state.

Please try like this and let me know if you face any issues.

**Comment by flyingboy007** [comment]
@anuj-verma  worked mate thank you.

**Comment by pedros007** [comment]
It seems this has improved with #419 .

**Comment by juanfurattini** [comment]
> @

You can call it like this `@booking.move_to_payment_response_received!(data)`

**Comment by artur79** [comment]
> This is the event:
> 
> ```ruby
> event :move_to_payment_response_received do
>   transitions from: :order_created, to: :payment_response_received,
>               :after => proc { |data| self.verify_payment_response(data)  }
> end
> ```
> 
> You can call it like this:
> 
> ```ruby
> @booking.move_to_payment_response_received!(data)
> ```

not sure if _.self_ is needed there
