### ISSUE TITLE
How do you override the base configurations globally?

### ISSUE THREAD

**Issue by hjeebus** [aasm/aasm#507]
i understand you can do the following:
```
aasm no_direct_assignment: true do
     state :one
     state :two
     state :three
...
end
```
instead of adding the `no_direct_assignment` flag to each modal, i would like to override the initial configuration value, preferably in an intializer. is this possible:
```
AASM::Configuration.no_direct_assingment = true
```

i also saw this line in the README:
> You can hide warnings by setting AASM::Configuration.hide_warnings = true

but, i'm not sure where to use that as its also raising errors for me.
```
$ bundle exex rails c
config/initializers/aasm.rb:1:in `<top (required)>': undefined method `hide_warnings=' for AASM::Configuration:Class
Did you mean?  with_warnings (NoMethodError)
```

**Comment by anuj-verma** [comment]
Hi @hjeebus ,
I checked the source code and found that currently AASM::Configuration class only implements setters/getters for `hide_warnings` as class variable.
All other configuration options like `whiny_transitions`, `no_direct_assignment` are instance methods.
Refer this: https://github.com/aasm/aasm/blob/master/lib/aasm/configuration.rb

I tried setting value of `AASM::Configuration.hide_warnings = true` in `config/initializers/aasm.rb` and its working fine as implemented.

I agree with you that we should have the feature to set all configuration options at global level like we have for `hide_warnings`.
@anilmaurya Thoughts ?

**Comment by Adi9** [comment]
What I did was set a global param in application.rb:
`module MyApp
    class Application
        ...
        AASM_PARAMS_HASH = { whiny_transitions: false, logger: Rails.logger, column: 'state' }`

and then in the model definition:

`class Model < ApplicationRecord
    ...
    aasm MyApp::Application::AASM_PARAMS_HASH do
        state ...`

**Comment by hjeebus** [comment]
this is like ~5 years old going to close.
