### ISSUE TITLE
What is the recommended approach for setting model state on events?

### ISSUE THREAD

**Issue by vincentwoo** [aasm/aasm#509]
Reading the docs, it appears that AASM is geared towards creating self-contained state machines inside ActiveRecord models. However, I think it would be useful to store side-effects as a result of transitions. For example:

```ruby
class Foo < ApplicationRecord
  include AASM

  aasm do
    state :opened, initial: true
    state :closed
   
    event :close do
      transition opened: closed
      self.closed_at = Time.now # this bit won't work because self is the AASM machine
    end
  end
end

foo = Foo.new
foo.close!
```

This seems like a common enough use-case but I can't figure out what the "official" way to achieve this should be. Am I missing something?

**Comment by anuj-verma** [comment]
Hi @vincentwoo,
As per docs, You can define a number of callbacks for your transitions. These methods will be called, when certain criteria are met, like entering a particular state, or after/before an event.

For setting `closed_at` you can define a callback like below.
```
class Foo < ApplicationRecord
  include AASM

  aasm do
    state :opened, initial: true
    state :closed
   
    event :close, after: :set_closed_time do
      transitions :from => :opened, :to => :closed
    end
  end
  
  def set_closed_time
    self.closed_at = Time.now
  end
end
```

**Comment by vincentwoo** [comment]
Alright, that makes sense. What is the purpose of the code that occurs within the `do` block of an event, then? What logic *is* supposed to occur there?

**Comment by anuj-verma** [comment]
Inside an `event` `do` block you can do the following:

1. Specify one or more transition between states.
Refer: https://github.com/aasm/aasm#transitions
2. Specify conditions i.e `guards` on transitions
Refer: https://github.com/aasm/aasm#guards

**Comment by vincentwoo** [comment]
Thank you. I appreciate the help!

**Comment by anilmaurya** [comment]
@anuj-verma 👍🏅

**Comment by wnm** [comment]
> Hi @vincentwoo,
> As per docs, You can define a number of callbacks for your transitions. These methods will be called, when certain criteria are met, like entering a particular state, or after/before an event.
> 
> For setting `closed_at` you can define a callback like below.
> 
> ```
> class Foo < ApplicationRecord
>   include AASM
> 
>   aasm do
>     state :opened, initial: true
>     state :closed
>    
>     event :close, after: :set_closed_time do
>       transitions :from => :opened, :to => :closed
>     end
>   end
>   
>   def set_closed_time
>     self.closed_at = Time.now
>   end
> end
> ```

Thanks so much, that was really helpful for me too. Quick question: We do have to hit `self.save` in `set_closed_time` to make in permanent, no?
