### ISSUE TITLE
after_commit does not work as expected in nested transactions

### ISSUE THREAD

**Issue by averell23** [aasm/aasm#536]
We are using aasm with activerecord and mysql/postgres for persistence. Today I found that the `after_commit` hook does not do what it says on the label, when you are in a nested transaction.

## What happens

The hook is called after the aasm_transaction is complete, but _before_ the outermost transaction is completed. This means that it will be called after a `RELEASE SAVEPOINT` but before the database transaction is `COMMIT`ed to the database.

## What I expected

I had expected that the hook is only called after the database transaction `COMMIT` is done, that is, after the outermost database transaction is complete. This is also how the ActiveRecord `after_commit` hook works.

## Was this means

Currently in an `after_commit` callback

* The database state may only be visible from the current thread (e.g. not in asynchronous processes)
* The current state may not actually be persisted, and can still be rolled back if an outer transaction fails

## See the code

https://github.com/aasm/aasm/blob/26219482f7cb50cfa49bff7474aacf045c42c205/lib/aasm/persistence/orm.rb#L134

**Comment by caalberts** [comment]
@averell23 I'm also facing this issue in my application. I'm curious if you managed to work around this issue, and how.

I have an aasm `after_commit` hook which spawns a sidekiq background job, taking in the ActiveRecord object id. Something like: `SomeJob.perform_async(self.id)`

I have occasionally encountered situation where the job is picked up by Sidekiq worker, before the object is persisted to the database, and the job fails with error saying `ActiveRecord::RecordNotFound: Couldn't find Object with 'id'=123`.

**Comment by averell23** [comment]
You can mitigate by not having calling the state change within another transaction, the hook works at expected if you call it outside a db transaction.

You could also work with the `ActiveRecord.after_commit` hook, but this would involve some manual work...

**Comment by FX-HAO** [comment]
A workaround
```
class AfterCommitWrap
  # If not in a transaction, the block will be executed instantly.
  def self.after_commit(&block)
    ActiveRecord::Base.transaction do
      ActiveRecord::Base.connection.add_transaction_record(new(&block))
    end
  end
end

event :complete, after_commit: :after_completion do
  transitions from: %i[checkout processing], to: :completed
end

def after_completion
  AfterCommitWrap.after_commit do
    # your code here
  end
end
```
I'd like someone could help to fix this issue :)

**Comment by stokarenko** [comment]
https://github.com/aasm/aasm/pull/666 has been reverted.

https://github.com/aasm/aasm/pull/668 will fix the issue once again, but without explicit AR dependency.

**Comment by mquan** [comment]
Any idea when a new version with the fix will be released?

**Comment by anilmaurya** [comment]
@mquan Thank you for the reminder

Just released AASM `5.1.0` with the fix

**Comment by yugandharbandi2220** [comment]
@anilmaurya It's not working for me even after upgrading to latest version

**Comment by stokarenko** [comment]
@anilmaurya did you added `after_commit_everywhere` gem as explicit Gemfile dependency?

As per Readme,

> Please note that :after_commit AASM callbacks behaves around custom implementation of transaction pattern rather than a real-life DB transaction. This fact still causes the race conditions and redundant callback calls within nested transaction. In order to fix that it's highly recommended to add gem 'after_commit_everywhere', '~> 1.0' to your Gemfile.

**Comment by yugandharbandi2220** [comment]
@stokarenko my bad, missed this. It's working after adding the dependency. Thanks for the help
