### ISSUE TITLE
Get list of states & permissible_states based on current state of an AASM object

### ISSUE THREAD

**Issue by jhilden** [aasm/aasm#54]
We have the use case where we want to display a `select` dropdown for the user to select from all the possible states to transition to.  For that we needed 2 things:  1) a list of all the states  2) a list of the states that the object could potentially transition to based on the current state.

This is the code that we came up with

```
def permissible_states_for_current_state
  aasm_permissible_events_for_current_state.map do |event|
    AASM::StateMachine[MyClass].events[event].instance_variable_get("@transitions").first.opts[:to]
  end
end

def states
  AASM::StateMachine[MyClass].states.map &:name
end

def not_permissible_states_for_current_state
  states - permissible_states_for_current_state
end

def states_for_select
  states.map{ |state| [I18n.t("#{state}"), state] }
end
```

And in the view

```
options_for_select(@my_object.states_for_select, selected: @my_object.state, disabled: @my_object.impossible_states)
```

The question is where there is already and easier/better way to do it, or if it would be possible to implement those two methods `aasm_permissible_states_for_current_state` and `aasm_states` within AASM?

**Comment by kendrikat** [comment]
And for anybody looking for a list of possible events: 
```
YourProcess.aasm.events.map(&:name)
```

**Comment by zx1986** [comment]
Why `aasm_states` didn't work anymore?

**Comment by Manifold0** [comment]
Second this. I still see the code for the method, but I seem to always get back the full State Machine object instead of the just the states.

**Comment by abigoroth** [comment]
Say we already have its event, then how can I get transitions? its "from" and "to"

**Comment by revof11** [comment]
> Why `aasm_states` didn't work anymore?

I switched my code to use this:

`available_states = MyObject.aasm.states.map(&:name).map(&:to_s)`

**Comment by gregblass** [comment]
Any idea how to do this if you've got multiple AASM state types on a class?

**Comment by smtlaissezfaire** [comment]
Note: these aren't the same:

```
Envelope.aasm.states.map(&:name)
Envelope.aasm.events.map(&:name)
```
