### ISSUE TITLE
Querying states

### ISSUE THREAD

**Issue by StaverDmitry** [aasm/aasm#542]
Hi! I love the way model states are hidden and accepted by getters\setters only but I have a question.
I recently had to make an sql query which had a `WHERE` clause with a state of my model. For starters I just used a string with my state name.
So the question simply is: is it the right way to do it? It feels like it's a better idea to get the state I need with some getter and a symbol kinda like enums do `Model.states(:cancelled)`.
I'm ok with how it is now, just wondering if maybe I'm missing something.

**Comment by darrenterhune** [comment]
Please use SOF for this type of question. Btw did you read about https://github.com/aasm/aasm#automatic-scopes ?

@anilmaurya close

**Comment by anilmaurya** [comment]
@StaverDmitry , Automatic scopes is the answer for your question.

Thank you @darrenterhune for pointing out.
