### ISSUE TITLE
Keeping state values as capitalized in DB

### ISSUE THREAD

**Issue by abhishekjain16** [aasm/aasm#543]
Hi, I was looking to implement this wonderful gem to my existing project. 
In my current project, the status column on which I am trying to add `aasm`, the values are saved as a capitalized string like 'Draft', 'Published' etc

How do I define my state in aasm so, that when an event is called, the value is saved correctly in capitalized form?

Thanks for the help.

**Comment by darrenterhune** [comment]
SOF is the place to ask questions like this. In regards to your problem... don't do that, just migrate your existing data to lower-case underscore. Something like this:

```ruby
Model.find_each do |model|
  model.update_column :whatever_your_status_attribute, model.underscore
end
```

@anilmaurya close

**Comment by anilmaurya** [comment]
@abhishekjain16 I agree with @darrenterhune , database should store not store capitalised strings .

Instead view helpers should capitalise state name whenever required.
