### ISSUE TITLE
Feature request: parameterized #may? method

### ISSUE THREAD

**Issue by Drenmi** [aasm/aasm#547]
Hello, and thanks again for an amazing gem!

I was hoping that, in addition to the dynamically generated methods, there'd be a parameterized method for checking if a transition is allowed, e.g.:

```ruby
machine.may?(:run)
```

At the moment we're left with having to resort to:

```ruby
machine.public_send("may_#{transition}?")
```

Thanks!

**Comment by pedros007** [comment]
@Drenmi I think you can do this already. Have you tried this:

```ruby
machine.aasm.may_fire_event? :run
```

**Comment by Drenmi** [comment]
I think that's exactly it, @pedros007. Thank you! 🙇 

It isn't quite clear if this is intended to be used publicly, but I think it fits the bill well enough for us that we're willing to take the small risk of the method's behaviour changing.
