### ISSUE TITLE
Bang method unexpectedly not raising RecordInvalid

### ISSUE THREAD

**Issue by cabello** [aasm/aasm#568]
Untested code but this is what I believe is the minimal scenario to reproduce this issue:

```ruby
class Foo < ActiveRecord::Base
  validates :transition_code, presence: true, if: :cancelled?

  aasm do
    state :initial, initial: true
    state :cancelled

    event :cancel do
      transitions from: :initial, to: :cancelled
    end
  end
end
```

### Expected result

`Foo.first.cancel!` to raise exception `RecordInvalid` missing `transition_code`.

### Actual result

`Foo.first.cancel!` returns `false`.

Also worth noting:

```ruby
foo = Foo.first
foo.may_cancel? # true
foo.cancel      # true
foo.save!       # raises ActiveRecord::RecordInvalid
```

### Gems 
- aasm (4.12.3)
- activerecord (5.1.4)

**Comment by jongirard** [comment]
Also experiencing this same issue with activerecord 4.2.0. Validations are not working at all.

**Comment by nedgar** [comment]
When using AASM with ActiveRecord (the norm), or any other persistence layer, I highly recommend using `whiny_persistence: true`, e.g.:
```ruby
aasm whiny_persistence: true do ...
```

Since AASM opens a write transaction on any state transitions, it's a lot safer to raise than to risk committing partial updates.

**Comment by anilmaurya** [comment]
@cabello @jongirard You will have to use `whiny_persistence: true`.
Thank you @nedgar .
