### ISSUE TITLE
Callback using class is not available on `event`

### ISSUE THREAD

**Issue by caalberts** [aasm/aasm#582]
This works,
```ruby
event :run do
  transitions :from => :running, :to => :finished, :after => LogRunTime
end
```

but this doesn't
```ruby
event :run, :after => LogRunTime do
  transitions :from => :running, :to => :finished
end
```

The documentation sounds like it should work.

> Callbacks
> You can define a number of callbacks for your events, transitions and states. These methods, Procs or classes will be called when certain criteria are met, like entering a particular state:

**Comment by anilmaurya** [comment]
@caalberts Which version of AASM you are using ? This is recently introduced in version 5.0.0 .

**Comment by bsimpson** [comment]
Late to respond but I ran into this as well. The interface has changed slightly in newer versions. As of 3.4.0 it looked like this instead:
```
event :run do
  transitions :from => :running, :to => :finished, :on_transition => Proc.new { |obj, *args| obj.method }
end
```
