### ISSUE TITLE
Events accept invalid "to" states

### ISSUE THREAD

**Issue by sypher7** [aasm/aasm#584]
### Description
Attempting to pass a `to_state` to an event that is not defined has unexpected results (it is interpreted as an argument, and a `nil` `to_state` is used).

### Steps to reproduce
1. Fire an event with an invalid `to_state` as the first parameter:
```
some_state_machine.run!(:foo)
```

### Expected Result
`AASM::InvalidTransition` should be raised.

### Actual Result
The first defined transition for the `from_state` is used, similar to how passing `nil` works.

### Digging Deeper
The source of this appears to be the code here:
https://github.com/aasm/aasm/blob/d23e75ef46c3a3f1a6bd66dba780e1fac506e44b/lib/aasm/core/event.rb#L131-L139

If the `to_state` argument to the `_fire` method is not `::AASM::NO_VALUE` or included in the event transition's `to` states, AASM assumes that this is simply part of the argument list.

### Solutions
This could probably be refactored a bit. Perhaps a check to see if the second argument is an options `Hash`, and allow for a `to_state` option that could be explicitly set, with the rest of the options passed through.

In lieu of any sort of major change here, the documentation could probably be updated:

> You can also pass in `nil` as the desired end state, and AASM will try to transition to the first end state defined for that event.

A caveat about invalid states could be added to expand on that.

I'd be happy to open a PR after some discussion on what should be done (if anything) about this.

Thanks!

**Comment by anilmaurya** [comment]
@sypher7 Thank you for reporting .
@skolsuper updated docs, therefore closing this issue.
