### ISSUE TITLE
AASM 5.0.1 does not respect validations

### ISSUE THREAD

**Issue by jongirard** [aasm/aasm#595]
My model has some basic validators, such as `validates_presence_of :name, :destination_url, :start_date, :end_date`

My aasm setup looks like: 
```
aasm :column => :status do
    state :draft, :initial => true
    state :published, :unpublished

    event :publish do
      transitions :from => [:draft, :unpublished], :to => :published
    end

    event :unplublish do
      transitions :from => :published, :to => :unpublished
    end
  end
```

Creating a new MarketingCampaign object...

`marketing = MarketingCampaign.new`

```
=> #<MarketingCampaign id: nil, author_id: nil, name: nil, destination_url: nil, start_date: nil, end_date: nil, filename: nil, content_type: nil, data: nil, status: "draft", internal_description: nil, created_at: nil, updated_at: nil> 
```
`marketing.publish` returns TRUE.

The validations are being completely skipped over and I cannot tell as for why.

**Comment by jongirard** [comment]
Just to note the same logic works with `state_machines` library and the validations do not fail there so I don't believe it is a problem with my model/controller setup specifically.

**Comment by BKSpurgeon** [comment]
are you able to spin up a minimal rails_app: `rails new marketing_campaign_app` with a test where  `marketing.publish` returns true?

**Comment by dave4u90** [comment]
@jongirard  `marketing.publish!` will give you error for validation,  `publish` just assigns the from state and involves checking that transition is allowed or not.

**Comment by nedgar** [comment]
Try using `whiny_persistence: true` as well. See https://github.com/aasm/aasm/issues/568#issuecomment-465840470

**Comment by anilmaurya** [comment]
@jongirard Validations are run when you save your changes. `marketing.publish` will only assign values, it is not saved in database.
You should use `marketing.publish!` along with `whiny_persistence: true` as pointed by @Siraris @dave4u90 & @nedgar . Thank you guys.
