### ISSUE TITLE
Previous failures appear in exception message when event has no applicable transitions

### ISSUE THREAD

**Issue by nedgar** [aasm/aasm#599]
If a transition fails due to a precondition failing, or an exception in an `after` callback, then a subsequent attempt to invoke the same event when there's no possible transition for the current state will raise an exception (as expected), but the exception's message lists the previous failure(s).

This is a gap in the earlier fix for https://github.com/aasm/aasm/issues/383.
FYI @anilmaurya.

Here is a standalone test case showing the problem.

```ruby
require "rails_helper"

class TestRecord
  include AASM

  aasm do
    state :a, initial: true
    state :b

    event :doit do
      transitions from: :a, to: :b, guard: :ok?
    end
  end

  def ok?
    false
  end
end

describe AASM do
  subject { TestRecord.new }

  it "clears previous failures" do
    expect { subject.doit }.to raise_error(AASM::InvalidTransition, "Event 'doit' cannot transition from 'a'. Failed callback(s): [:ok?].")
    subject.aasm.current_state = :b
    expect { subject.doit }.to raise_error(AASM::InvalidTransition, "Event 'doit' cannot transition from 'b'.")
  end
end
```

With AASM 5.0.1, this fails due to the 2nd exception's message listing the failed callbacks from the previous attempt.

**Comment by nedgar** [comment]
Suggested fix is to clear *all* failures across all events and their transitions at the start of event processing.

**Comment by nedgar** [comment]
One workaround is to define a [replacement base class](https://github.com/aasm/aasm#extending-aasm):

```ruby
class AASMBase < AASM::Base
  def initialize(klass, name, state_machine, options = {}, &block)
    super

    # callbacks are instance-eval'ed on the instance of the class defining the state machine, so capture self
    base = self
    before_all_events { base.clear_failures }
  end

  def clear_failures
    events.each do |event|
      event.transitions.each do |transition|
        next unless transition.failures.any?
        Rails.logger.debug("Clearing #{transition.failures.size} earlier failures for transition in " \
          "#{klass.name}: #{transition.from} -> #{transition.to}")
        transition.failures.clear
      end
    end
  end
end
```

Then uses that in your state machines with:
```ruby
aasm with_klass: AASMBase do ...
```

**Comment by anilmaurya** [comment]
@nedgar Can you raise a PR for `Suggested fix is to clear _all_ failures across all events and their transitions at the start of event processing.`

It make sense to fix it in AASM instead of asking everyone to extend AASM and fix it in their application.

**Comment by nedgar** [comment]
@anilmaurya please see proposed fix in https://github.com/aasm/aasm/pull/600
