### ISSUE TITLE
How to add conditional transition

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [aasm/aasm#605]
So let's say I call an event call `charge!` now I don't want the change to be conditional.

If the response is correct I want to move to success else move to failed how would I model this?

```ruby
event :charge, before: :charge_card do
      transitions from: :charge, to: :[:error, :success]
end
```

**Comment by davefp** [comment]
Sounds like you need a guard:  https://github.com/aasm/aasm#guards

Something like this would work:
```ruby
event :charge, before: :charge_card do
  transitions from: :charge, to: :success, if: valid_charge?
  transitions from: :charge, to: :error
end

...

def valid_charge?
  // logic here
end
```

Note that the order is important, as AASM will stop looking for transitions if one succeeds.

**Comment by ankitsinghaniyaz** [comment]
This is what I'm doing, I just thought there could be another way to do this.

**Comment by AvikantSrivastava** [comment]
@davefp  
If the `valid_charge ` return as `false` can we trigger another event?

I want to change state if the condition is true, if not then trigger another event (that contains multiple transitions, so don't wanna repeat state transition again which is already defined)

> Sounds like you need a guard: https://github.com/aasm/aasm#guards
> 
> Something like this would work:
> 
> ```ruby
> event :charge, before: :charge_card do
>   transitions from: :charge, to: :success, if: valid_charge?
>   transitions from: :charge, to: :error
> end
> 
> ...
> 
> def valid_charge?
>   // logic here
> end
> ```
> 
> Note that the order is important, as AASM will stop looking for transitions if one succeeds.

**Comment by davefp** [comment]
@AvikantSrivastava that I don't know, I'm afraid
