### ISSUE TITLE
Subclass setting the status gives NoMethodError

### ISSUE THREAD

**Issue by texpert** [aasm/aasm#609]
In a project, there are two Ohm::Model classes - one inheriting from another. The AASM is defined on the superclass. Just trying to create a new instance of the sub-class with  FactoryGirl, gives the following error:

```
NoMethodError:
       super: no superclass method `status=' for #<ProductSubclass:0x007fad65b9b800>
       Did you mean?  status
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/aasm-5.0.2/lib/aasm/base.rb:63:in `block in initialize'
     # ./app/models/product.rb:245:in `before_create'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/ohm-contrib-2.0.1/lib/ohm/callbacks.rb:28:in `save'
     # /Users/abranzeanu/.rvm/gems/ruby-2.3.4@rails32/gems/factory_girl-4.3.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
```

After thorough debugging, I have found a workaround - changing the line https://github.com/aasm/aasm/blob/master/lib/aasm/base.rb#L63, which is originally `super(state_name)` to `state_name || super(state_name)`. This is working well along with a lot of other state machines defined in the project.

Was this a good workaround or is there some other way to deal with the issue?

**Comment by dennym** [comment]
This sounds similar to my issue #616 . Is you superclass an `abstract_class`?

**Comment by texpert** [comment]
@dennym , nope, it is a legit Ohm::Model class.

**Comment by dennym** [comment]
Dug a bit deeper and wrote it in my issue. Your temp solution also fixes my issue. But no idea if this affects something else....

**Comment by dennym** [comment]
Hey, can you give #620 a try and check if your issue still exists?

**Comment by texpert** [comment]
@dennym , I am quite busy this days, I will try to find some time in a week.

**Comment by texpert** [comment]
Thanks, @dennym, https://github.com/aasm/aasm/pull/620 has fixed the issue. Great work!

Closing the issue and waiting for a new release.

**Comment by anilmaurya** [comment]
@texpert Thank you for reporting this issue.

New version `5.0.4` is released which includes fix for this issue.
