### ISSUE TITLE
Multiple state machines in one model? 

### ISSUE THREAD

**Issue by etagwerker** [aasm/aasm#61]
Hi, 

I am migrating from `state_machine` to `aasm` but I've noticed an issue when trying to use more than one state machines in my model. 

My code looks like this: 

```
class Student
  # State Machine #1 
  aasm(column: 'tuition_state') do
    ...
  end

  # State Machine #2 
  aasm(column: 'attendance_state') do
    ...
  end
```

I am calling an event from `tuition_state` but my test fails because it tells me it cannot transition from one state to the other. 

Somehow it gets confused and an event from state machine #1 is considering states from state machine # 2.

So, are multiple state machines in one model supported? 

I could refactor my code and move the second state machine to another model, but I'd prefer not to do that for now. 

Please let me know.

Thanks,
Ernesto

**Comment by posgarou** [comment]
@alto Agreed: this would be very helpful.

**Comment by oozzal** [comment]
@alto The only reason I'm still using state_machine. Any plans on supporting this?

**Comment by alto** [comment]
@oozzal Yes, it's currently planned for the `4.2.0` release (see #158 for details). But to be honest, it's quite a lot of work, since it is almost a complete rewrite of _AASM_.

**Comment by gregblass** [comment]
Hey @etagwerker! Funny to see you here, haha. I found this via Google...just ran into this myself.
