### ISSUE TITLE
Only allow auto-save

### ISSUE THREAD

**Issue by arthurnn** [aasm/aasm#610]
Sorry if this is not the right channel to ask this question (maybe request this feature)

I find some folks sometimes misuse the non-bang methods, and assume things would either get saved, and even worst, sometimes call save afterwards, but then the `after_commit` event callbacks would not get run.
I wonder if there is a way to force users to only use the bang(auto-save) methods, and let the other version raise, or even not exist.
Is that possible today?

**Comment by anilmaurya** [comment]
Hi @arthurnn 
This is not possible as of today.

I am not sure if this feature is going to help lots of people OR it will confuse lots of people.

**Comment by arthurnn** [comment]
Indeed I think would be a weird API. 
For now, I will add some internal mechanism to do that. Not sure will made it to the gem.
If you have interests on it, or more people do, re-open this and I can send a PR

Thanks

**Comment by mdayaram** [comment]
If possible, I would love to be able to provide an option in my `aasm <options>` block to forbid the use of the non-autosave methods.  For anything that's ActiveRecord-backed, I can't imagine a time when I'd ever use the non-autosave methods, but I have tons of times where I've made mistakes by using them.

**Comment by Samsinite** [comment]
Late to the game here, but couldn't you just mark the non-bang methods as private?
```rb
  private :some_event
```
