### ISSUE TITLE
Possibly incorrect documentation for passing arguments to events?

### ISSUE THREAD

**Issue by maknz** [aasm/aasm#613]
The README says that to pass arguments to events, which in turn get passed to its callbacks, they are supplied alongside the end state when triggering the event, e.g:

```rb
job = Job.new
job.run(:running, :argument)
```

In cases where the machine is deterministic, or we're happy to let AASM pick the first end state, we can - according to the docs - pass in `nil` for the end state:

```rb
job = Job.new
job.run(nil, :argument)
```

However, this doesn't seem to be the case. `nil` is what gets passed to my callback, not `:argument`.

Changing the code to call the event solely with the argument I want passed to the callback does work; the callback gets called with `:argument`:

```rb
job = Job.new
job.run(:argument)
```

I prefer this behaviour over having to include `nil` all the time when I've got a deterministic state machine and the end state is never ambiguous, but it goes against what the docs say.

**Comment by shioyama** [comment]
I'm struggling with this now too. The documentation doesn't seem to clarify what arguments are passed into what things, and what it does say doesn't seem to line up with the behaviour I see.

e.g. the `before` block on an `event` is passed the arguments, but it seems that e.g. `before_success` does not receive anything...

**Comment by anilmaurya** [comment]
@maknz Fixed Readme.
 @shioyama This issue is fixed on master branch.
