### ISSUE TITLE
Allow skipping definition of unprefixed method names, for multiple state machines

### ISSUE THREAD

**Issue by wvengen** [aasm/aasm#614]
Since [4.3.0](https://github.com/aasm/aasm/blob/master/CHANGELOG.md#430) (#61, #158, PR #240) multiple state machines per class [are supported](https://github.com/aasm/aasm#multiple-state-machines-per-class). But if two state machines have the same state or event, methods are being redefined, and warnings are emitted.

For example:
```ruby
class Foo
  include AASM

  aasm :first do
    state :start
    event :continue
  end

  aasm :second do
    state :start
    event :continue
  end
end
```

Emits the warnings:
```
WARN -- : Foo: overriding method 'start?'!
WARN -- : Foo: overriding method 'may_continue?'!
WARN -- : Foo: overriding method 'continue!'!
WARN -- : Foo: overriding method 'continue'!
```

The definition of overlapping scopes can be [skipped](https://github.com/aasm/aasm#automatic-scopes) with `create_scopes: false`. To solve this, I would suggest to allow skipping the definition of unprefixed method names and only create prefixed method names (like `may_start_first?`).

To keep backward compatibility, this could be enabled by an aasm option like `namespace_methods: true` (only honoured when `namespace` is given too).

Would this be a welcome change?

**Comment by wvengen** [comment]
Somehow in an ActiveRecord model that includes `AASM`, I find that I have both namespaced and un-namespaced methods (so in the above example, if the class would be an AR model, I would see `may_continue?` as well as `may_continue_first?` and `may_continue_second?`.

**Comment by ralfthewise** [comment]
It also seems like the automatic scopes should have the namespace suffix when the `namespace` option is given...

**Comment by axsuul** [comment]
Also running into this and I think having an option `create_only_namespace_scopes: true` would be great

This issue was also brought up here: https://github.com/aasm/aasm/issues/519

**Comment by axsuul** [comment]
I'm finding that this seems to be a good compromise

```ruby
aasm :status do
  event :finish
end

aasm :sync_status, namespace: :sync do
  event :finish_sync
end
```

**Comment by luchiago** [comment]
Hello. This still need help ?

**Comment by anilmaurya** [comment]
I think @axsuul solution is fine, `namespace` option should be used in case of similar state or event name.
Thank you @axsuul @luchiago

**Comment by euanlau** [comment]
Hi @axsuul, wouldn't your workaround create a redundant 'finish_sync_sync' method?
