### ISSUE TITLE
No brainer issue

### ISSUE THREAD

**Issue by arabakevin** [aasm/aasm#615]
HI all,
When i follow the documentation, and i add the different status as indicated.

My model
```
class JoinRequest
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps
  include AASM
  field :aasm_state, type: String
  aasm do
    state :in_progress, initial: true
    state :accepted
    state :rejected
    event :mark_as_accepted do
      transitions from: :in_progress, to: :accepted
    end
    event :mark_as_rejected do
      transitions from: :in_progress, to: :rejected
    end
  end

  # ~~~~ Virtual Fields ~~~~

  # ~~~~ Fieds ~~~~~
  field :requester_id, type: String
  field :organisation_id, type: String

  # ~~~~ Associations ~~~~
  belongs_to :organisation
  belongs_to :requester, class_name: 'User'

end
```
And i try to used aasm state with the console.
You can see an example: 

`
irb(main):017:0> jr = JoinRequest.new
=> #<JoinRequest id: "7MKZ44Ek74KfWR">

irb(main):018:0> jr.aasm_state
=> nil

irb(main):019:0> jr.valid?
=> true

irb(main):020:0> jr.aasm_state
=> nil
`

So the initializer of the field didn't work. And i can't continue to update the field.
Can you help me ?
Thanks.
Best regards.
kevin

**Comment by zedtux** [comment]
I started a new Rails project with RethinkDB/nobrainer and I'm using aasm. All is working just fine.

Have a look at https://gitlab.com/pharmony/commis.

**Comment by arabakevin** [comment]
Based on your example, all is working now.
Thanks for your help.
