### ISSUE TITLE
abstract_class leads to super: no superclass method `state=' 

### ISSUE THREAD

**Issue by dennym** [aasm/aasm#616]
I made a small [test repository](https://github.com/dennym/aasm_inheritance).
When Adding the state machine to an abstract class the setter method cannot be found

Person inherits from User which is abstract and has the state machine defined.
When creating a person with `Person.create!(state: 'active')` I get the error 
`(super: no superclass method `state=' for #<Person:0x000055e84b3ba090>)`

When deactivating the `self.abstract_class` of User it works but this is not an option. Is this an intended behavior?

Edit:
After digging further because I remembered using this couple of years back I found out this behavior changed from 4.1.1 to 4.2.

Edit2:
Only bigger thing that changed from 4.1.1 to 4.2 is https://github.com/aasm/aasm/commit/daf13541bc12848a9f2268738a5d8575b8d79dc5

Edit3:
As mentioned in #609 when changing the https://github.com/dennym/aasm/blob/master/lib/aasm/base.rb#L63 to `state_name || super(state_name)` this behavior works. No idea about the side effects. When running the specs against active_record of this gem with the change 14 specs are failing.

**Comment by anilmaurya** [comment]
Hi @dennym ,

Thank you for reporting this issue & providing test repository to reproduce this issue.

I have fixed this issue & released new version `5.0.3` .

**Comment by dennym** [comment]
Wow thanks a lot. I was already digging through code but couldn't find a clean way of keeping all additional specs green. I am curious if this [abstract class check ](https://github.com/aasm/aasm/blob/ebf54ebc2d80efe5ba1cd30e6e68adfcdf267977/lib/aasm/base.rb#L57) breaks the `AASM::NoDirectAssignmentError` functionality. I don't use this feature but could be that someone else does.

**Comment by anilmaurya** [comment]
This  fix won't break `no_direct_assignment` config. I already tested it. 
If your issue is resolved then please close this issue.
Thank you.

**Comment by dennym** [comment]
Sorry I have to reopen this. Not sure if this is something that should be considered.
In my test repository I had `User` inherit from `ApplicationRecord` So the check if the superclass is abstract is always true. When doing something like this

```ruby
module Lifecycles
  module User
    extend ActiveSupport::Concern

    included do
      include AASM

      aasm column: 'state' do
        state :inactive, initial: true
        state :active
      end
    end
  end
end

class User < ActiveRecord::Base
  include Lifecycle::User
  self.abstract_class = true
  self.table_name = 'users'
end

class Person < User
end

Person.create(state: 'inactive')
```

It won't work since at the point of including the The lifecycle file the class is not defined as abstract yet. The specs you added for the fix are green because you insert the aasm definition after `self.abstract_class`. And includes should be always on top of a class.

This was working with `4.1.1` as expected. Can't we just drop the `no_direct_assignment` "feature"?
I don't see functionality use for this. Shouldn't this something rubocop catches or is just written in the code style guide of each company?

**Comment by anilmaurya** [comment]
I just tested AASM with your test repository, it is working fine for me.

Did you tried and got same error ?

**Comment by dennym** [comment]
Change the user.rb to inherit from `ActiveRecord::Base` instead of `ApplicationRecord` ... My repository is right now a false positive.

**Comment by dennym** [comment]
@anilmaurya made a PR no idea if this is viable. It keeps the new features and restores the v4.1.1 behavior.

**Comment by anilmaurya** [comment]
@dennym Merged your PR.

Regarding `no_direct_assignment` feature. We can not drop a feature in minor release.
I will think about it at the time of releasing `6.0.0`

**Comment by dennym** [comment]
:heart: Sure understandable this needs to be deprecated first before dropping it. Come back to me any time about this part.

**Comment by anilmaurya** [comment]
Sure, will get back to you.

Thank you for contributing and helping out .♡
