### ISSUE TITLE
Rails 5.2 not tested

### ISSUE THREAD

**Issue by waghanza** [aasm/aasm#623]
Hi,

I can see on `CI` that `rails` **5.2** is not tested

Is there any reason to by-pass those tests ?

Regards,

**Comment by anilmaurya** [comment]
Where did you see that Rails `5.2` is by-passed.
Test are configured to run for Rails `5.1` at the moment.

**Comment by waghanza** [comment]
in  `CI` -> https://travis-ci.org/aasm/aasm

**Comment by anilmaurya** [comment]
Tests are configured using Appraisal. https://github.com/aasm/aasm/blob/master/Appraisals

Feel free to contribute and add Rails `5.2`
