### ISSUE TITLE
How to get model object from event 

### ISSUE THREAD

**Issue by Mracobes9** [aasm/aasm#629]
Hi. How i can to get model object  for which i trigger event ? I want to update model object attribute in event

**Comment by anilmaurya** [comment]
You can do something like this
```
event :run, before: Proc.new {|*args| before_call(*args) } do
...
...
end

def before_call(obj)
  obj.update_attributes({name: 'Test'})
end

o = Object.new
o.run!(o)

**Comment by Mracobes9** [comment]
@anilmaurya thanks, but i need to make it in event handler. Maybe i can to send object id as params ?

**Comment by anilmaurya** [comment]
I Didn't understood your question.

**Comment by Mracobes9** [comment]
@anilmaurya how i can to make the following think 
```
event :test do
    var = some_param
end
...
obj.event(some_param)
```

**Comment by anilmaurya** [comment]
Its not possible, please read https://github.com/aasm/aasm#usage for proper usage.
