### ISSUE TITLE
Running tests with Docker doesn't work

### ISSUE THREAD

**Issue by lesin** [aasm/aasm#640]
Several issues occured while building an image.
Ex. issue with permissions and with locales:

<img width="1132" alt="aasm1" src="https://user-images.githubusercontent.com/1833428/61294320-da120f00-a7d5-11e9-9c63-c2fff658b267.png">
<img width="1134" alt="aasm2" src="https://user-images.githubusercontent.com/1833428/61294328-de3e2c80-a7d5-11e9-811e-2caac45475ee.png">

**Comment by anilmaurya** [comment]
Fixed in #641
