### ISSUE TITLE
Group/zipping the permitted event and permitted state.

### ISSUE THREAD

**Issue by aviisekh** [aasm/aasm#656]
If suppose my application is in applied state, I need to make a hash where I should know that if I trigger hire, it should move to hired, or if I reject, it should move to rejected state.

So Need to compute execute hash like 
Application.first.aasm.permitted_transitions 
[{event: hire, state: hired}, {event: reject, state: rejected}]

**Comment by anilmaurya** [comment]
AASM does not support this feature at the moment.
I think its good to have feature, PR is welcome.
