### ISSUE TITLE
Ruby 2.7 warnings

### ISSUE THREAD

**Issue by hwo411** [aasm/aasm#672]
**Describe the bug**
Right now having `after_enter` method with keyword generates a warning with Ruby 2.7:
``usr/local/bundle/ruby/2.7.0/gems/aasm-5.0.8/lib/aasm/core/invokers/literal_invoker.rb:32: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`

**To Reproduce**
```ruby
class Buggy
  include AASM

  aasm do
    state :not_buggy, initial: true
    state :buggy, after_enter: :display_bug

    event :bug do
      transitions from: :not_buggy, to: :buggy
    end
  end

  def display_bug(arg:)
  end
end

Buggy.new.bug!(arg: 123)
```

I didn't test this code, this is an extraction from our working code.

**Expected behavior**
No Ruby 2.7 warnings are shown.

**Comment by anilmaurya** [comment]
@the-spectator Interested in resolving this issue ?

**Comment by hwo411** [comment]
I also discovered this topic: https://bugs.ruby-lang.org/issues/16463
Might be relevant. (I discovered similar problem with just using `delegate:`).

**Comment by the-spectator** [comment]
@anilmaurya Yes, I will definitely try to resolve the issues.

**Comment by anilmaurya** [comment]
Hi @hwo411 

I checked this issue. You should not use keyword argument in `display_bug` method
To solve your issue, update your code like this

```
class Buggy
  include AASM

  aasm do
    state :not_buggy, initial: true
    state :buggy, after_enter: :display_bug

    event :bug do
      transitions from: :not_buggy, to: :buggy
    end
  end

  def display_bug(args)
    # Now use args[:arg]
  end
end

Buggy.new.bug!(arg: 123)
```
Closing this issue, please reopen if it does not solve your problem.

**Comment by hwo411** [comment]
@anilmaurya does this mean that aasm won't support keyword arguments for transitions? It's worth adding to the documentation then.

I'm not familiar with aasm code, but brief check showed me that `**kwargs` are never passed for callbacks and adding them might solve the issue in way that it works properly for my example. Is it something that can still be considered?

**Comment by anilmaurya** [comment]
@hwo411 
Yes, we need to update docs mentioning not to use keywords argument.

Currently AASM support array of arguments, using hash & keyword argument together will throw this warning in 2.7. 
Later on in 3.0 it will start throwing error therefore we should not allow it.

**Comment by tisba** [comment]
@anilmaurya Since I just stumbled across this, currently the README actually recommends using keyword arguments (https://github.com/aasm/aasm#parameters):
![CleanShot 2021-03-15 at 15 20 21](https://user-images.githubusercontent.com/75156/111168073-03360480-85a2-11eb-97b7-88cdbd190de1.png)

**Comment by anilmaurya** [comment]
Thank you @tisba for pointing it out, I have corrected it.

**Comment by Flixt** [comment]
Just to get this clarified: Hash/Keyword arguments, like in the example below, in guards, callbacks etc. are currently not supported, correct? (although they just work in Ruby <= 2.6)

```ruby
class Job
  include AASM

  aasm do
    state :idle
    state :running

    event :run do
      transitions from: :idle, to: :running do
        after do |reason:|
          self.reason = reason
          puts "reason was #{reason}"
        end
      end
    end
  end
end

job = Job.new
job.run(reason: 'my-reason')

# => Ruby 2.6 just works
# => Ruby 2.7 prints deprecation warning as described in this issue
# => Ruby 3.0 raises "missing keyword: :reason (ArgumentError)"
```

Out of curiosity, and because I personally like the keyword style much more: Will it stay this way? Is there a technical reason for that? Or is it "just" a hell lot of work? I would be happy to help to get this working if it is something the maintainers would consider valuable. I'd even say it is something, that should be supported in a way newer Ruby version would expect it to work. There is no way, I as a reader of that code, could know this would blow up on newer Rubies.

**Comment by tchak** [comment]
I also don't understand why it is closed as a "won't fix". Would it be possible to provide a bit more details on why?

**Comment by Rmpanga** [comment]
@tchak  and @Flixt This is a Ruby 2.7 and Ruby 3.0+ issue. They deprecated (in 2.7) and removed (in 3.0+) the use of keyword arguments.   

Source: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
