### ISSUE TITLE
Run an event inside "after event", raises AASM::UndefinedState - Eventless tranistion support?

### ISSUE THREAD

**Issue by nerburish** [aasm/aasm#682]
Hi all.

I have an aasm model similar to this:

```
  aasm column: :status, enum: true do
    state :pending, initial: true
    state :reserving
    state :reserved

    event :reservate, before: :perform_reservation!, after: :reservation_finish do
      transitions from: :pending, to: :reserving
    end

    event :reservation_finish do
      transitions from: :reserving, to: :reserved
    end
 end
```

My goal is to fire the event reservation_finish automatically when the transition to reserving is finished.
This pattern is called in state machines as Transient transition (or Automatic tranistion).

In aasm context, I tried to accomplish this calling reservation_finish via after event reservate  callback.
Surprisingly, call an event inside event context raises the error:
     AASM::UndefinedState:
       State : doesn't exist

I checked why is the source of the exception and I noticed that inside callcbaks the model status attribute becomes nil and consequently raises this error becuase in fact tries to trasient from nil to reserved.

Is this the expected behaviour or its a bug?

There is an alternative to implement the "transient transition" affect?

Greetings

**Comment by anilmaurya** [comment]
Hi @nerburish 

I tried to reproduce your issue with following script:

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activerecord', '5.1.4'
  gem 'sqlite3', '1.3.13'
  gem 'aasm', '5.0.8'
  gem 'pry'
  gem 'pry-nav'
end

require 'active_record'
require 'sqlite3'
require 'aasm'

puts "AASM: #{AASM::VERSION}"

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Migration.create_table :flows do |t|
  t.string :name
  t.string :aasm_state
  t.integer :state
end


class Flow < ActiveRecord::Base
  include AASM

  enum state: {
    ready: 0,
    running: 1,
    completed: 2
  }

  aasm column: :state, enum: true do 
    state :ready, initial: true
    state :running
    state :completed

    event :start, after: :done! do
      transitions from: :ready, to: :running
    end

    event :done do
      transitions from: :running, to: :completed
    end
  end
end


flow = Flow.create
p flow
flow.start!
p flow.reload
```

It's working correctly without any issue.

Can you give similar script to reproduce your issue ?

**Comment by anilmaurya** [comment]
@nerburish , I am closing this issue.
Feel free to open it with script to reproduce it.

**Comment by nerburish** [comment]
Hi, thanks.
Was a problem with my enum configuration.

Greetings
