### ISSUE TITLE
`human_state_name` ignores display name

### ISSUE THREAD

**Issue by ashleyHutton** [aasm/aasm#684]
**Describe the bug**
Using the `.human_state_name` on an instance's current state, it does not use the custom display name, if there is one present. It will use the localized state name.

**To Reproduce**

Overriding a state's display name:
```ruby
state :enabled, display: "Active"
state :pending, initial: true
```

```
[3] pry(main)> o.aasm.current_state
=> :enabled
[4] pry(main)> o.aasm.human_state
=> "Enabled"
[6] pry(main)> obj.aasm.states.detect { |s| s.name == obj.aasm.current_state }.display_name
=> "Active"
```

**Expected behavior**
I'd expect `o.aasm.human_state` to return the custom display name, `"Active"`

**Additional context**
It looks like the `human_state` comes from the `human_state_name` method in the `Localizer` class:

https://github.com/aasm/aasm/blob/f7231d1c319aa90fdd5079b6c153a873637c2166/lib/aasm/localizer.rb#L11-L18

Potentially the default could be changed to: `:default => state.display_name`.

**Comment by anilmaurya** [comment]
Thank you for reporting it.

AASM `5.1.1` is released with the fix
