### ISSUE TITLE
Why is AASM enforcing savepoint transactions when nesting ActiveRecord transactions?

### ISSUE THREAD

**Issue by eric-christian** [aasm/aasm#685]
Hello,

not really a bug more a question. 😃 

We have a Rails project with CockroachDB.
When we started using AASM, the DB raised "too many nested transactions". So we looked up the traces and noticed that AASM uses savepoint transactions when there is already an active ActiveRecord transaction (nesting transactions).
CockroachDB, at least in the version we are currently at, is only able to support one savepoint at a time.

```ruby
# That is ok for cockroachdb
MyModel.transaction do # BEGIN
  MyModel.transaction(requires_new: true) do # CREATE SAVEPOINT A
    ...
  end
end

# That is not ok for cockroachdb
MyModel.transaction(requires_new: true) do # BEGIN
  MyModel.transaction(requires_new: true) do # CREATE SAVEPOINT A
    MyModel.transaction(requires_new: true) do # CREATE SAVEPOINT B -> Exception
      ...
    end
  end
end
```
So, while it is usually a totally legit way of nesting transactions, we were still wondering why it is necessary for AASM to actually enforce a savepoint?

Why not simply go with the default behavior from ActiveRecord and join the transactions into one?
```ruby
MyModel.transaction(requires_new: false) do # BEGIN
  MyModel.transaction(requires_new: false) do # no-op
    MyModel.transaction(requires_new: false) do # no-op
      ...
    end
  end
end
```

The problem with "too many nested transactions" came because we are already using the only available savepoint transaction to leverage the better performance during serialisation errors from cockroachdb. That serialisation error comes from the transaction-isolation-level "serialized" which is the only supported isolation from cockroachdb. It is something the app has to handel. That means that within the business logic, no further savepoints can be created.

I have changed the configuration option `requires_new_transaction:` to `false`. So far everything seems to work fine.
Am I missing something?
Are any features from AASM depending on the nested savepoint transactions?
What is the benefit that makes the overhead (extra statements send to the database) worse it enforcing savepoints per default?
Did i miss that point in the documentation? 🤔 

Happy to hear from you and thank you all for your work on this awesome gem! 😃 

Best regards,
Eric

**Comment by anilmaurya** [comment]
Hi @eric 

> Why not simply go with the default behavior from ActiveRecord and join the transactions into one?

AASM provides configuration flag `requires_new_transaction` for this, and you have correctly set it to `false`.

> Are any features from AASM depending on the nested savepoint transactions?

As such AASM feature is not dependent on it, but it is useful when you are firing AASM event from inside transaction block.
For example:
```
job = Job.create
job.transaction do
  job.run!
  # some other activity
end
```
Rollback of transaction will not work as expected if you set it to false, for more details check Nested transaction section in https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html

> What is the benefit

Rollback for Nested transactions works correctly. 

Let me know if you have any doubts.

**Comment by eric-christian** [comment]
Hi @anilmaurya ,

Thank you for your feedback! 😃 

Is this about `ActiveRecord::Rollback`? Is AASM raising `ActiveRecord::Rollback` somewhere?

Otherwise i can't see the point in your example. If `job.run!` or `# some other activity` raises an exception (not AR::Rollback), my expectation would be that the transaction startet at `job.transaction do` would be rolled back. Assuming that it is the most outer transaction. That would be the case with and without `requires_new_transaction`.

What makes `job.run!` different from `job.save!` in the context of transactional behavior?

I still have the impression that i am missing something here. 🤔 


Best regards,
Eric

**Comment by nikolai-b** [comment]
We have had issues with SAVEPONTS in posgresql (see [[1](https://about.gitlab.com/blog/2021/09/29/why-we-spent-the-last-month-eliminating-postgresql-subtransactions)], [[2](https://postgres.ai/blog/20210831-postgresql-subtransactions-considered-harmful)] and others) and I found our SAVEPOINTS coming from this gem.  I can turn them off via the config, thank you for the option but the documentation seems to suggest there is a general issue with setting `requires_new_transaction` as does [this spec](
https://github.com/aasm/aasm/blob/f8cf86510e914a5521b228b931a49a56fef456e4/spec/unit/persistence/active_record_persistence_spec.rb#L565-L578).  I cannot re-create that spec when using postgresql as persistance layer, as in the worker is left in `sleeping` state when I run it.  I was going to suggest that you just update the documentation that you only need to use `requires_new_transaction` if you are using `ActiveRecord::Rollback`.  @eric-christian are you able to re-create that spec with CockroachDB?  Did you turn off `requires_new_transaction`?

**Comment by eric-christian** [comment]
@nikolai-b We have `requires_new_transaction: false` everywhere.
