### ISSUE TITLE
Can we the ability to run "entry" actions

### ISSUE THREAD

**Issue by dsomel21** [aasm/aasm#693]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I am looking for the ability to run some "fire and forget" functions once I am in a specific state. 

**Describe alternatives you've considered**

This is what I have right now. The problem is that when user is in `in_correct_day,` I have no idea how I can fire a function. 

```ruby
    aasm do
      state :idle, initial: true
      state :in_correct_stage, :in_correct_day, :ready_to_schedule_notification

      # IDLE STATE
      event :STAGE_TRANSITION do
        transitions from: :idle, to: :in_correct_stage do
          guard do
            is_unit_in_correct_stage?
          end
        end
        transitions from: :idle, to: :idle
      end

      event :DAY_TRANSITION do 
        transitions from: :in_correct_stage, to: :in_correct_day do
          guard do
            is_unit_in_correct_day?
          end
        end
        transitions from: :in_correct_day, to: :in_correct_stage
      end
    end
```
 
This is the way it is done is XState: 
```javascript
{  
  inCorrectStage: {
    on: {
      DAY_TRANSITION: {
        target: 'inCorrectDay',
        cond: isUnitInDay,
      },
    },
  },
  inCorrectDay: {
    entry: sendNotification,
  },
}
```

It's pretty clever because you define the events in the STATE {} definition. **Is there any other way I can** run 

**Additional  context**
I am still new to FSM but [according to the W3](https://www.w3.org/TR/scxml/), `onentry` is a bonus feature that State Machine frameworks offer (in addition to state and transition).

**Comment by anilmaurya** [comment]
Hi @dsomel21 

You can use callbacks to do that, for example:

```
aasm do
      state :idle, initial: true
      state :in_correct_stage
      state :in_correct_day, after_enter: :sendNotification
      state :ready_to_schedule_notification
.....
.....
```

**Comment by dsomel21** [comment]
Wow, I looked at that function so many times too! Thank you @anilmaurya! This is great!
