### ISSUE TITLE
Only "before_enter" callback works on the initial state

### ISSUE THREAD

**Issue by IanVaughan** [aasm/aasm#738]
The following code works
```ruby
aasm do
  state :created, initial: true, before_enter: :save_status_change
end

def save_status_change
...
end
```
But I cannot save relational data within the callback method as the parent is not yet saved:
```
ActiveRecord::RecordNotSaved:You cannot call create unless the parent is saved
```

Ideally some other lifecycle event would also work, eg `:after`.
Attempting to use any other event results in no method call, eg this code runs fine:
```ruby
state :created, initial: true, after: proc { raise }
```

**Comment by ChandanChainani** [comment]
@IanVaughan from version `3.0.13` [`active-record transaction`](https://github.com/aasm/aasm#transaction-support) support as been added

As per transaction-support you can use `after_commit` or `after_all_transactions` callback.

You can also check `after_all_events` life-cycle method.
