### ISSUE TITLE
Documentation does not match the current release

### ISSUE THREAD

**Issue by MarcLapierre** [aasm/aasm#740]
The current documentation references a [new feature](https://github.com/aasm/aasm/pull/677) for automated timestamps, however this does not exist in the current 5.1.1 release.

I had to go dig through the gem's source to figure out why this wasn't working. It would be great if either

- the gem version gets bumped when a new feature is added, or
- the documentation clearly states that the feature is only available on the master branch

**Comment by anilmaurya** [comment]
Thank you for reporting this issue.

I will release new version tomorrow with this feature include.

**Comment by anilmaurya** [comment]
New version `5.2.0` is released with this feature.
