### ISSUE TITLE
after_commit deprecation - what is actually deprecated?

### ISSUE THREAD

**Issue by ryanuber** [aasm/aasm#761]
Hi! First and foremost, thank you for AASM. We've used it extensively with great success.

Recently we upgraded an older app to version 5.2.0 of AASM, from 4.x. In doing so, we began noticing [the deprecation notice](https://github.com/aasm/aasm/blob/252ade3a20dd86abed3ec76b965f85da530e2611/lib/aasm/persistence/active_record_persistence.rb#L75-L76) for `:after_commit`, and the suggestion for using the `after_commit_everywhere` gem. For the app in question, however, we are very well aware of the potential race conditions and other quirks using `:after_commit`, and over time we've built safeguards ourselves that prevent us from performing dangerous actions in nested transactions and other such cases.

My question is, what exactly is deprecated? Is use of `after_commit` in general deprecated? Can we expect a breaking change in the future? Or is it simply use of `after_commit` without `after_commit_everywhere`? We're trying to gauge whether we should proactively start refactoring, even though `after_commit` is working well for us without `after_commit_everywhere`.

Thanks for any insight you can offer!

**Comment by MuhammadRazaAslam** [comment]
@anilmaurya @Envek Can anyone of you explain the reason?

**Comment by Envek** [comment]
Hi @ryanuber, @MuhammadRazaAslam.

> My question is, what exactly is deprecated?

As far as I understand, use of `after_commit` without [after_commit_everywhere](https://github.com/Envek/after_commit_everywhere) gem is deprecated.

As per [README § Transaction support](https://github.com/aasm/aasm#transaction-support):

> Please note that `:after_commit` AASM callbacks behaves around custom implementation of transaction pattern rather than a real-life DB transaction. This fact still causes the race conditions and redundant callback calls within nested transaction. In order to fix that it's highly recommended to add `gem 'after_commit_everywhere', '~> 1.0'` to your `Gemfile`.

See #666 and #668 for more context.

**Comment by MuhammadRazaAslam** [comment]
@Envek Thanks for the explanation.

**Comment by MuhammadRazaAslam** [comment]
@Envek Do you know why https://github.com/aasm/aasm/commit/59ebeca066486958e96fbc62c10474292d61b55e has been reverted?

**Comment by anilmaurya** [comment]
Thank you @Envek 

@ryanuber I am closing this issue, please reopen if you need more explanation

**Comment by route** [comment]
Still not clear why we need this gem since AR has it's own after_commit which I thought is gonna be used.
