### ISSUE TITLE
Wrong count on where clausure

### ISSUE THREAD

**Issue by fedeagripa** [aasm/aasm#766]
**Describe the bug**
When I query my model 

**To Reproduce**
1. Create a model with 3 possible status with AASM
2. Create a bunch of records
3. Exec Model.count
4. Exec Model.where(status: 0).count && Model.where(status: 1).count && Model.where(status: 2).count
5. Check sum does not match step 3 count

**Expected behavior**
Model.count to match the sum of all the possible status

**Screenshots**
<img width="1154" alt="Screen Shot 2022-01-08 at 21 47 36" src="https://user-images.githubusercontent.com/23194751/148664818-91ceafbe-cc90-402e-907e-efadb55d01fc.png">

**Additional context**
My model only has 3 possible status:
`enum status: { active: 0, inactive: 1, canceled: 2 }`

**Comment by ChandanChainani** [comment]
@fedeagripa please can you check if there are records with `null` status.

**Comment by ChandanChainani** [comment]
@fedeagripa please can you share sample example.

**Comment by fedeagripa** [comment]
@ChandanChainani please check my picture example in the description, I'm doing a `Subscription.all` and then filtering in memory by the aasm column and the count is ok, but when counting through aasm is wrong. That is more than enough to see there is an error in the aasm filtering/count

**Comment by ChandanChainani** [comment]
@fedeagripa the screenshot you shared it just include activerecord sql, please can you share how you are using aasm.

**Comment by fedeagripa** [comment]
@ChandanChainani  pretty straight forward as described in the project readme with the default `status` column: 

![Screen Shot 2022-02-23 at 11 49 50 AM](https://user-images.githubusercontent.com/23194751/155343320-14fb53fc-98a6-4e77-8051-401b10e0a75d.png)

**Comment by ChandanChainani** [comment]
@fedeagripa how the aasm state change is being triggered.

**Comment by fedeagripa** [comment]
Closing this as there is no interest in fixing this, only asking useless questions to keep quicking this longer. Will start looking for a good alternative to state management

**Comment by anilmaurya** [comment]
Hi @fedeagripa 

Please understand that first we need to reproduce this bug at our end so that we can fix it.
If you can give a failing test case then we won't have to ask any other questions.

Thanks, Anil.

**Comment by fedeagripa** [comment]
@anilmaurya I have already provided the steps in my description, if you just run `rails new` and install aasm you can reproduce it, also you have my code in the upcoming comment.
I tried changing statuses in multiple ways (through active admin, directly from the console, and dug into your codebase also to figure out possible causes before filing this).

You don't seem to even have used the simple code I shared and the test case in my description. To change statuses I'm just following your documentation so you have all you need

**Comment by anilmaurya** [comment]
Hi @fedeagripa 

Code provided by you is not enough to reproduce this issue. We don't know what is data type of your `status` column. 

If `status` type is string and you are using without `enum: true` then it won't work

Ref :
<img width="963" alt="Screenshot 2022-04-14 at 10 31 39 PM" src="https://user-images.githubusercontent.com/1912864/163438662-1bc027f1-ceb4-4c59-aa36-48d2dac3838d.png">

I asked for failing test case because I know you won't be able to share full source code for debugging.

Also, language of your comments is inappropriate. We won't accept such behaviour. 
You are free to look for a good alternative for state management

**Comment by fedeagripa** [comment]
@anilmaurya is a bit weird that you decided to copy just part of the documentation, just read 1 line bellow: 
```Furthermore, if your column has integer type (which is normally the case when you're working with Rails enums), you can omit :enum setting --- AASM auto-detects this situation and enabled enum support. If anything goes wrong, you can disable enum functionality and fall back to the default behavior by setting :enum to false.```

My enums are stored as integers as rails usual behavior, otherwise, I would have fixed that and probably I wouldn't have raised this issue.

Also in the doc you say you are supposed to auto-detect enums if we use them in the rails way, so why are you saying it wont work? weird....

Finally please point me out my inappropriate language, maybe you don't like my imperative way of writing, but that's a way of writing, not inappropriate language.

**Comment by anilmaurya** [comment]
> Also in the doc you say you are supposed to auto-detect enums if we use them in the rails way, so why are you saying it wont work? weird...

I said, if `status` type is `string` and you are using without `enum: true` then it won't work

Can you give me a sample code in this format ?
```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activerecord', '5.1.4'
  gem 'sqlite3', '1.3.13'
  gem 'aasm', '5.2.0'
  gem 'pry'
  gem 'pry-nav'
end

require 'active_record'
require 'sqlite3'
require 'aasm'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')


ActiveRecord::Migration.create_table :flows do |t|
  t.integer :state
end

class Flow < ActiveRecord::Base
  include AASM

  enum state: {
    ready: 0,
    running: 1,
    completed: 2
  }

  aasm column: :state, enum: true do 
    state :ready, initial: true, display: 'First'
    state :running, display: 'Second'
    state :completed

    event :start, after: :done! do
      transitions from: :ready, to: :running
    end

    event :done do
      transitions from: :running, to: :completed
    end
  end
end

5.times { Flow.create(state: 'ready')}
10.times { Flow.create(state: 'running')}
15.times { Flow.create(state: 'completed') }

p Flow.count # => 30
p Flow.where(state: 0).count # => 5
p Flow.where(state: 1).count # => 10
p Flow.where(state: 2).count # => 15
```
