### ISSUE TITLE
Upon upgrade to 5.3.0, `fire!` requires Symbol and raises error with String

### ISSUE THREAD

**Issue by norman** [aasm/aasm#787]
As of the 5.3.0 release, which includes #753 , `fire!` requires a symbol rather than a string. If an event name is passed as a String rather than a Symbol, it raises `AASM::UndefinedState`.

This is my excerpted setup from my application with steps to reproduce.

```ruby
class CampaignMember
  aasm column: :status, timestamps: true, whiny_persistence: true do
    state :invited

    event :invite do
    transitions to: :invited
    end
  end
end

c = CampaignMember.first
c.aasm.fire!(:invite) # works as expected
c.aasm.fire!("invite")
AASM::UndefinedState: State :invite! doesn't exist
```
I would either expect the code to raise `ArgumentError` if you intend to force the type as Symbol rather than String, or for `fire` to cast a String to a Symbol internally. My preference as a user of this library would be for silent casting to Symbol, but either choice would make sense to me.

I'm not sure if this was silently failing with a String before, or whether the changes in #753 included breaking changes.

If the maintainers agree this is an issue to be fixed then I am happy to do the work and open a pull request. If it turns out I have misunderstood the library and this is in fact an issue in my code then my apologies for the wasted time.

**Comment by anilmaurya** [comment]
Hi @norman 

Thanks for raising this issue.

You are correct, AASM should cast to symbol and this is broken after #753 .

Please go ahead and raise a PR to fix it.
