### ISSUE TITLE
Active Record upgrade 5 to 6 : AASM  does not clear the activerecord cache after calling an event 

### ISSUE THREAD

**Issue by mohamedrez** [aasm/aasm#815]
**Describe the bug**
We are upgrading activerecord from 5 to 6 and we started seeing lot of failling specs, during the investigation it shows that after calling an event it changes the state on the DB but when fetching the object using activerecord it returns its value from the cache

**Comment by RodrigoMNardi** [comment]
I have this same issue in Rails 7 and Ruby 3.0. Sometimes it doesn't clear the cache.

**Comment by mohamedrez** [comment]
@RodrigoMNardi I managed to find the issue it was more related to rails than AASM hence closing this issue, the fix was to update from active record 6.0 to the latest 6 and configuring the connection adapter to not use the legacy one.
